### ISSUE TITLE
Create proper error if entry doesn't exist

### ISSUE THREAD

**Issue by Jeltje** [ga4gh/dockstore#1050]
### Actual behaviour
`dockstore tool cwl --entry registry.hub.docker.com/ucsctreehouse/fusion:0.3.1`
results in 
```
Invalid tag
io.swagger.client.ApiException: Invalid version.
        at io.swagger.client.ApiClient.invokeAPI(ApiClient.java:713)
        at io.swagger.client.api.ContainersApi.cwl(ContainersApi.java:207)
        at io.dockstore.client.cli.nested.ToolClient.getDescriptorFromServer(ToolClient.java:1006)
        at io.dockstore.client.cli.nested.AbstractEntryClient.handleDescriptor(AbstractEntryClient.java:313)
        at io.dockstore.client.cli.nested.AbstractEntryClient.descriptor(AbstractEntryClient.java:436)
        at io.dockstore.client.cli.nested.AbstractEntryClient.processEntryCommands(AbstractEntryClient.java:237)
        at io.dockstore.client.cli.Client.run(Client.java:689)
        at io.dockstore.client.cli.Client.main(Client.java:602)
```

### Preferred behaviour
`ERROR: this entry does not exist`
The `invalid version` threw me for a loop, I thought it meant the java version.  And `invalid tag` is too obscure.

### Environment (Browser or OS and Dockstore version)
Ubuntu 16.04, dockstore 1.3.0

**Comment by garyluu** [comment]
Error message seems better:

```gluu@ODL-GARYLUU:~/testCLI$ ./dockstore tool cwl --entry registry.hub.docker.com/ucsctreehouse/fusion:potato
dockstore needs to be on PATH for certain commands to work (like --upgrade)
io.swagger.client.ApiException: Invalid or missing tag potato.
	at io.swagger.client.ApiClient.invokeAPI(ApiClient.java:737)
	at io.swagger.client.api.ContainersApi.cwl(ContainersApi.java:213)
	at io.dockstore.client.cli.nested.ToolClient.getDescriptorFromServer(ToolClient.java:1007)
	at io.dockstore.client.cli.nested.AbstractEntryClient.handleDescriptor(AbstractEntryClient.java:315)
	at io.dockstore.client.cli.nested.AbstractEntryClient.descriptor(AbstractEntryClient.java:438)
	at io.dockstore.client.cli.nested.AbstractEntryClient.processEntryCommands(AbstractEntryClient.java:239)
	at io.dockstore.client.cli.Client.run(Client.java:691)
	at io.dockstore.client.cli.Client.main(Client.java:604)
```
