### ISSUE TITLE
Retrieval of RSS seems broken from Discourse

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1053]
## Bug Report

Discussion forum is creating threads both by visiting pages that do not yet have threads and via RSS feed. Only the latter actually properly sets thread titles and provides a snippet of content. 
Take a look at discourse and see if it is possible to only have threads created via RSS.

**Comment by denis-yuen** [comment]
This is still going on

**Comment by denis-yuen** [comment]
More info, this might be an issue on the discourse side actually failing to even try to read our RSS

```
 default: FinalDestination could not resolve URL (invalid URI): https://dockstore.org:8443/metadata/rss 
```
```
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/logster-1.2.9/lib/logster/logger.rb:93:in `add_with_opts'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/logster-1.2.9/lib/logster/logger.rb:50:in `add'
/usr/local/lib/ruby/2.4.0/logger.rb:534:in `warn'
/var/www/discourse/lib/final_destination.rb:298:in `public_send'
/var/www/discourse/lib/final_destination.rb:298:in `log'
/var/www/discourse/lib/final_destination.rb:151:in `resolve'
/var/www/discourse/app/jobs/scheduled/poll_feed.rb:104:in `fetch_rss'
/var/www/discourse/app/jobs/scheduled/poll_feed.rb:90:in `parsed_feed'
/var/www/discourse/app/jobs/scheduled/poll_feed.rb:76:in `topics'
/var/www/discourse/app/jobs/scheduled/poll_feed.rb:30:in `poll_feed'
/var/www/discourse/app/jobs/scheduled/poll_feed.rb:17:in `execute'
/var/www/discourse/app/jobs/base.rb:134:in `block (2 levels) in perform'
/var/www/discourse/vendor/bundle/ruby/2.4.0/gems/rails_multisite-2.0.4/lib/rails_multisite/connection_management.rb:63:in `with_connection'
/var/www/discourse/app/jobs/base.rb:129:in `block in perform'
/var/www/discourse/app/jobs/base.rb:125:in `each'
/var/www/discourse/app/jobs/base.rb:125:in `perform'
/var/www/discourse/app/jobs/base.rb:180:in `perform'
/var/www/discourse/lib/scheduler/manager.rb:91:in `process_queue'
/var/www/discourse/lib/scheduler/manager.rb:37:in `block in initialize'
```

**Comment by denis-yuen** [comment]
Yup. 

Moving it to https://gist.githubusercontent.com/denis-yuen/862f2cc2a49506214a9cabc90a202d45/raw/126c1463a4c8191d04f7b6473e70a62661098419/rss.xml seemed to temporarily "solve" the problem

**Comment by denis-yuen** [comment]
Also needs to take into account tool or workflow name from Dockstore side, but this is less problematic

**Comment by denis-yuen** [comment]
Works with a nginx proxy, but we have a new problem
