### ISSUE TITLE
Running CWL-runner with extra tags seems broken 

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1072]
### Expected behaviour

Launches tool properly

### Actual behaviour

```
$ cwltool --help
...
  --no-compute-checksum
                        Do not compute checksum of contents while collecting
                        outputs
$ dockstore tool launch --local-entry Dockstore.cwl --json 10MB_s3cmd.json 
Creating directories for run of Dockstore launcher at: /home/alpine/dockstore-dd/datastore//launcher-130bcac0-c46e-4cee-94cc-0b73d631f7c6
Provisioning your input files to your local machine
Calling out to a cwl-runner to run your tool
########### WARNING ###########
You are using extra flags for CWLtool which may not be supported. Use at your own risk.
--no-compute-checksum
java.lang.UnsupportedOperationException
    at java.util.AbstractList.add(AbstractList.java:148)
    at java.util.AbstractList.addAll(AbstractList.java:260)
    at io.github.collaboratory.LauncherCWL.runCWLCommand(LauncherCWL.java:590)
    at io.github.collaboratory.LauncherCWL.run(LauncherCWL.java:223)
    at io.dockstore.client.cli.nested.AbstractEntryClient.handleCWLLaunch(AbstractEntryClient.java:1139)
    at io.dockstore.client.cli.nested.AbstractEntryClient.launchCwl(AbstractEntryClient.java:1073)
    at io.dockstore.client.cli.nested.AbstractEntryClient.checkEntryFile(AbstractEntryClient.java:929)
    at io.dockstore.client.cli.nested.AbstractEntryClient.launch(AbstractEntryClient.java:1027)
    at io.dockstore.client.cli.nested.AbstractEntryClient.processEntryCommands(AbstractEntryClient.java:252)
    at io.dockstore.client.cli.Client.run(Client.java:689)
    at io.dockstore.client.cli.Client.main(Client.java:602)
```

### Environment (Browser or OS and Dockstore version)
Dockstore 1.3.0 (works in 1.2.0)

Discovered by @keiranmraine

**Comment by denis-yuen** [comment]
Additionally: documentation says to break using commas which isn't correct

**Comment by keiranmraine** [comment]
The update you pushed to me worked as intended.

**Comment by garyluu** [comment]
Looks like it works with 1.3.3
