### ISSUE TITLE
Javascript expressions for secondaryFiles in CWL

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1175]
### Expected behaviour

We would need a Javascript engine to understand the expression and create a list/array of possible input files.

### Actual behaviour

The expression is not understood to be an expression and you get 
```
java.lang.IllegalArgumentException: Illegal character in path at index 46: myfile.bam$(self.basename + self.nameext.replace('m','i'))
at java.net.URI.create(URI.java:852)
at io.dockstore.common.FileProvisioning.provisionInputFile(FileProvisioning.java:228)
```

### Steps to reproduce the behaviour 

Use a javascript expression in a secondary file, something like 
```
inputs:
  input_path:
    type: File
    doc: "Path to the input [b|cr]am file"
    secondaryFiles: $(self.basename + self.nameext.replace('m','i'))
    inputBinding:
      prefix: --input
      position: 1
```

**Comment by drjsanger** [comment]
An example can be found in [dockstore-cgpbigwig](https://github.com/cancerit/dockstore-cgpbigwig).
Specifically in [bam2bw.cwl](https://github.com/cancerit/dockstore-cgpbigwig/blob/develop/cwls/bam2bw.cwl#L32-L39)
