### ISSUE TITLE
wdl4s.parser not compatible with Cromwell 30.2 workflows

### ISSUE THREAD

**Issue by wshands** [ga4gh/dockstore#1211]
## Bug Report
Dockstore fails to run a WDL with a workflow output section using Cromwell 30.2.
Copy Cromwell 30.2 library over Cromwell 29 so that Dockstore uses Cromwell 30.2
cp ~/.dockstore/libraries/cromwell-30.2.jar ~/.dockstore/libraries/cromwell-29.jar

Run the following WDL:

task hello_world {
    String hello_input
    command {echo '${hello_input}' > output_file.txt
    }

    output {
      File salutation = 'output_file.txt'
    }
}

workflow wf {
  call hello_world

  output {
    File outfile = "output_file.txt"
  }
}

with this input:
{
  "wf.hello_world.hello_input": "Hello World"
}

### Expected behaviour
Using java and Cromwell 30.2 succeeds:
java -jar ~/.dockstore/libraries/cromwell-30.2.jar run bug.wdl -i bug.json

### Actual behaviour
Using Dockstore fails:
ubuntu@ip-172-31-0-216:~/wdl-debugging$ dockstore workflow launch --debug --local-entry bug.wdl --json bug.json

...

wdl4s.parser.WdlParser$SyntaxError: Unrecognized token on line 16, column 18:

    File outfile = "output_file.txt"
                 ^
        at wdl4s.parser.WdlParser.unrecognized_token(WdlParser.java:6171)
        at wdl4s.parser.WdlParser.lex(WdlParser.java:6244)
        at wdl4s.AstTools$.getAst(AstTools.scala:135)
        at wdl4s.WdlNamespace$.wdl4s$WdlNamespace$$load(WdlNamespace.scala:200)
        at wdl4s.WdlNamespace$.load(WdlNamespace.scala:188)
        at wdl4s.NamespaceWithWorkflow$.load(WdlNamespace.scala:302)
        at io.dockstore.client.Bridge.getInputFiles(Bridge.scala:85)
        at io.dockstore.client.cli.nested.AbstractEntryClient.launchWdlInternal(AbstractEntryClient.java:1292)
        at io.dockstore.client.cli.nested.WorkflowClient.checkEntryFile(WorkflowClient.java:382)
        at io.dockstore.client.cli.nested.WorkflowClient.launch(WorkflowClient.java:346)
        at io.dockstore.client.cli.nested.AbstractEntryClient.processEntryCommands(AbstractEntryClient.java:252)
        at io.dockstore.client.cli.Client.run(Client.java:689)
        at io.dockstore.client.cli.Client.main(Client.java:602)

(Attach tool/workflow documents or links where applicable to help us reproduce your issue)

### Environment (Browser or OS and Dockstore version)
Linux ubuntu 16.04
Dockstore 1.3.6

Describe your operating system (relevant for CLI and launcher) or your web browser (name and version, relevant for the Dockstore website)

**Comment by coverbeck** [comment]
Probably the same thing, but just in case, convert also fails on the original WDL that I believe Walt narrowed down this bug report from:

```
~$ dockstore workflow convert entry2json --entry github.com/DataBiosphere/topmed-workflows/Functional_Equivalence:1.0.0 > Dockstore.json
~$ cat Dockstore.json
Unrecognized token on line 264, column 28:

    File duplicate_metrics = MarkDuplicates.duplicate_metrics
                           ^
null
```

**Comment by denis-yuen** [comment]
Functional on staging with API 1.5.0-alpha.4, UI 2.2.0-alpha.3
```
$ dockstore workflow convert entry2json --entry github.com/DataBiosphere/topmed-workflows/Functional_Equivalence:1.0.0 > Dockstore.json
$ cat Dockstore.json 
{
  "PairedEndSingleSampleWorkflow.flowcell_unmapped_bams": "Array[File]",
  "PairedEndSingleSampleWorkflow.known_indels_sites_VCFs": "Array[File]",
  "PairedEndSingleSampleWorkflow.wgs_evaluation_interval_list": "File",
  "PairedEndSingleSampleWorkflow.increase_disk_size": "(optional) Int?",
  "PairedEndSingleSampleWorkflow.wgs_coverage_interval_list": "File",
  "PairedEndSingleSampleWorkflow.MarkDuplicates.read_name_regex": "(optional) String?",
  "PairedEndSingleSampleWorkflow.agg_preemptible_tries": "Int",
...
```
