### ISSUE TITLE
Dockstore (or maybe cwltool), compatibility issues with python 3/anaconda

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1242]
### Expected behaviour

Not entirely sure, ideally it would just work. But there could be legitimate compatibility issues that should be warned about more clearly. Looks like even `cwltool --version` is having issues

### Actual behaviour

```
(python3-6-dockstore-staging) boconnor@UCSC-MacBook-Pro 20180326_demo$ dockstore workflow launch --entry github.com/denis-yuen/dockstore-workflow-md5sum-unified:1.2.0 --json md5sum.json
problems running command: cwltool --version
stderr for command:
Traceback (most recent call last):
  File "//anaconda/envs/python3-6-dockstore-staging/bin/cwltool", line 7, in <module>
    from cwltool.main import main
  File "//anaconda/envs/python3-6-dockstore-staging/lib/python3.6/site-packages/cwltool/main.py", line 22, in <module>
    import schema_salad.validate as validate
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "//anaconda/envs/python3-6-dockstore-staging/lib/python3.6/site-packages/past/translation/__init__.py", line 341, in load_module
    mod = imp.load_module(fullname, *self.found)
  File "//anaconda/envs/python3-6-dockstore-staging/lib/python3.6/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "//anaconda/envs/python3-6-dockstore-staging/lib/python3.6/imp.py", line 172, in load_source
    module = _load(spec)
  File "//anaconda/envs/python3-6-dockstore-staging/lib/python3.6/site-packages/schema_salad/validate.py", line 3, in <module>
    import avro.schema
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "//anaconda/envs/python3-6-dockstore-staging/lib/python3.6/site-packages/past/translation/__init__.py", line 402, in load_module
    code = compile(source, self.pathname, 'exec')
  File "//anaconda/envs/python3-6-dockstore-staging/lib/python3.6/lib2to3/fixes/fix_operator.py", line 782
    % (json_string, e)), None, sys.exc_info()[2]
                       ^
SyntaxError: invalid syntax

java.lang.RuntimeException: problems running command: cwltool --version
at io.cwl.avro.Utilities.executeCommand(Utilities.java:96)
at io.github.collaboratory.cwl.cwlrunner.CWLToolWrapper.checkForCWLDependencies(CWLToolWrapper.java:32)
at io.dockstore.client.cli.Client.checkForCWLDependencies(Client.java:447)
at io.github.collaboratory.cwl.CWLClient.launch(CWLClient.java:92)
at io.dockstore.client.cli.nested.WorkflowClient.launch(WorkflowClient.java:352)
at io.dockstore.client.cli.nested.AbstractEntryClient.processEntryCommands(AbstractEntryClient.java:220)
at io.dockstore.client.cli.Client.run(Client.java:695)
at io.dockstore.client.cli.Client.main(Client.java:606)
Caused by: org.apache.commons.exec.ExecuteException: problems running command: cwltool --version (Exit value: 1)
at io.cwl.avro.Utilities.executeCommand(Utilities.java:92)
... 7 more
```

Encountered by @briandoconnor

**Comment by denis-yuen** [comment]
For now, FAQ entry on how we do with Anaconda and/or python 3.
Might need to borrow the group laptop

**Comment by garyluu** [comment]
I can reproduce the error in Linux VM.  With our version of cwltool in Dockstore 1.4.1, the workaround is to install avro-cwl==1.8.3.  https://github.com/common-workflow-language/cwltool/issues/524 .  We should probably have 2 requirements file, one for python 2 and one for python 3.

**Comment by denis-yuen** [comment]
Linking to #1220 for information. This is annoying. We may need to test once with both pythons and serve up both requirements? Ugh

**Comment by garyluu** [comment]
Also added this to the primer

**Comment by denis-yuen** [comment]
Was able to reproduce and run dockstore ( 1.5.0-beta.3)  in python3
