### ISSUE TITLE
Info call is too aggressive with security

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#127]
It looks like one of our command paths is too aggressive with security. Make sure that tool launching (works) with no access to a particular container aside from public ones. 

ex:
```
$ dockstore launch --entry quay.io/collaboratory/seqware-bwa-workflow:latest --json Dockstore.json

Exception: io.swagger.client.ApiException: Forbidden: please check your credentials.
io.swagger.client.ApiException: Forbidden: please check your credentials.
        at io.swagger.client.ApiClient.invokeAPI(ApiClient.java:532)
        at io.swagger.client.api.ContainersApi.getContainerByToolPath(ContainersApi.java:121)
        at io.dockstore.client.cli.Client.getCWLFromServer(Client.java:879)
        at io.dockstore.client.cli.Client.launch(Client.java:570)
        at io.dockstore.client.cli.Client.main(Client.java:1302)



$ dockstore info quay.io/collaboratory/seqware-bwa-workflow
Could not find container
```

FYI for @adamstruck

**Comment by denis-yuen** [comment]
Adding to this, a user is only added to a user list when they have access via the owning quay.io organization. This is inappropriate and should be made public actually when just attempting to read metadata as opposed to editing it.
