### ISSUE TITLE
Bunny through Dockstore output provisioning

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1317]
### Expected behaviour
Output file provisioning should work on Bunny when there's a metadata field.  

### Actual behaviour
The below works with cwltool through Dockstore CLI for dockstore-tool-md5sum but not bunny:
```
{
  "input_file": {
        "class": "File",
        "path": "md5sum.input"
    },
    "output_file": {
        "class": "File",
        "metadata": "eyJvbmUiOiJ3b24iLCJ0d28iOiJ0d28ifQ==",
        "path": "/tmp/md5sum.txt"
    }
}

```
The bunny error is:
```
Executing: /home/gluu/.dockstore/libraries/rabix-1.0.3/rabix-cli-1.0.3/rabix --basedir /home/gluu/dockstore-tool-md5sum/datastore//launcher-e33cca21-0ac6-4523-bd82-7afcd81042c8/working/ /home/gluu/dockstore-tool-md5sum/Dockstore.cwl /home/gluu/dockstore-tool-md5sum/datastore//launcher-e33cca21-0ac6-4523-bd82-7afcd81042c8/workflow_params.json
Exception in thread "main" java.lang.ClassCastException: java.lang.String cannot be cast to java.util.Map
	at org.rabix.bindings.cwl.helper.CWLFileValueHelper.getMetadata(CWLFileValueHelper.java:187)
	at org.rabix.bindings.cwl.helper.CWLFileValueHelper.createFileValue(CWLFileValueHelper.java:280)
	at org.rabix.bindings.cwl.CWLValueTranslator.translateToCommon(CWLValueTranslator.java:54)
	at org.rabix.bindings.cwl.CWLValueTranslator.translateToCommon(CWLValueTranslator.java:66)
	at org.rabix.bindings.cwl.CWLBindings.translateToCommon(CWLBindings.java:193)
	at org.rabix.cli.BackendCommandLine.main(BackendCommandLine.java:408)
```

The below works for both Bunny and cwltool:
```
{
  "input_file": {
        "class": "File",
        "path": "md5sum.input"
    },
    "output_file": {
        "class": "File",
        "path": "/tmp/md5sum.txt"
    }
}
```

**Comment by denis-yuen** [comment]
Obsolete with #1543
