### ISSUE TITLE
Login with Google

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1370]
### Desired behaviour

Implement with login creating brand new accounts for each Google login. 
Implement account linking on the Accounts page. 
Follow-up with login matching you to existing accounts with linked Google credentials.
(i.e. sign in with either GitHub or Google leading to same Dockstore account)

**Comment by denis-yuen** [comment]
Seems broken with logging in with Google only.
```
webservice_1     | ERROR [2018-07-20 21:00:16,750] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: a5dc6767dcccf344
webservice_1     | ! java.lang.NullPointerException: null
webservice_1     | ! at io.dockstore.webservice.SimpleAuthenticator.initializeUserProfiles(SimpleAuthenticator.java:89)
webservice_1     | ! at io.dockstore.webservice.SimpleAuthenticator_$$_jvst5a5_c._d8initializeUserProfiles(SimpleAuthenticator_$$_jvst5a5_c.java)
webservice_1     | ! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
webservice_1     | ! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```

Subsequently, no login name, no profile picture, etc.

**Comment by denis-yuen** [comment]
@agduncan94   FYI, this was the issue that I was discussing at stand-up. 
Present on staging

**Comment by denis-yuen** [comment]
Debugging together, looks like culprit is somehow tokens are created without a valid user id. 
Seems odd, probably 2 action items
1) Experiment with failed logins of various kinds
2) Add migration to delete orphaned tokens and add constraint

useful sql query
```
select * from token where userid not in (select id from enduser);
```

**Comment by denis-yuen** [comment]
Google login seems fairly robust now
