### ISSUE TITLE
Give TESK + Cromwell tes/cwl-tes a shot?

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1417]
### Desired behaviour

OICR will have a small Kubernetes cluster. Give https://github.com/EMBL-EBI-TSI/TESK and Cromwell TES a try https://cromwell.readthedocs.io/en/develop/backends/TES/ to test out verified WDL (and future, CWL) workflows.

Also https://github.com/common-workflow-language/cwl-tes might be a simple thing to try out as well.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-347)
┆Issue Type: Story
┆Issue Number: DOCK-347

**Comment by denis-yuen** [comment]
This might be an issue with TESK ( https://github.com/EMBL-EBI-TSI/TESK ) as opposed to Cromwell, so not sure where to report this or whether there's a config issue. 

Specifically, I'm using version 31 of Cromwell using the TES back-end as documented at https://cromwell.readthedocs.io/en/develop/backends/TES/

TESK is configured against MiniKube 
minikube version: v0.27.0

There's the following output 
```
 java -Dconfig.file=cromwell.conf  -jar cromwell-31.1.jar run Dockstore.wdl  --inputs input.json 
[2018-05-23 17:05:35,03] [info] Running with database db.url = jdbc:hsqldb:mem:2a59374c-56c1-41a7-9095-617e4028da3c;shutdown=false;hsqldb.tx=mvcc
[2018-05-23 17:05:39,14] [info] Running migration RenameWorkflowOptionsInMetadata with a read batch size of 100000 and a write batch size of 100000
[2018-05-23 17:05:39,15] [info] [RenameWorkflowOptionsInMetadata] 100%
[2018-05-23 17:05:39,22] [info] Running with database db.url = jdbc:hsqldb:mem:1168ba9d-82a5-4fa8-bbb4-395a33275813;shutdown=false;hsqldb.tx=mvcc
[2018-05-23 17:05:39,46] [info] Slf4jLogger started
[2018-05-23 17:05:39,58] [info] Metadata summary refreshing every 2 seconds.
[2018-05-23 17:05:39,61] [info] KvWriteActor configured to flush with batch size 200 and process rate 5 seconds.
[2018-05-23 17:05:39,61] [info] WriteMetadataActor configured to flush with batch size 200 and process rate 5 seconds.
[2018-05-23 17:05:39,62] [info] CallCacheWriteActor configured to flush with batch size 100 and process rate 3 seconds.
[2018-05-23 17:05:40,09] [info] JobExecutionTokenDispenser - Distribution rate: 50 per 1 seconds.
[2018-05-23 17:05:40,10] [info] SingleWorkflowRunnerActor: Submitting workflow
[2018-05-23 17:05:40,14] [info] WDL (Unspecified version) workflow 730729a9-5dbc-455f-84ee-cbcbbbf08b38 submitted
[2018-05-23 17:05:40,14] [info] SingleWorkflowRunnerActor: Workflow submitted 730729a9-5dbc-455f-84ee-cbcbbbf08b38
[2018-05-23 17:05:40,14] [info] 1 new workflows fetched
[2018-05-23 17:05:40,14] [info] WorkflowManagerActor Starting workflow 730729a9-5dbc-455f-84ee-cbcbbbf08b38
[2018-05-23 17:05:40,15] [info] WorkflowManagerActor Successfully started WorkflowActor-730729a9-5dbc-455f-84ee-cbcbbbf08b38
[2018-05-23 17:05:40,15] [info] Retrieved 1 workflows from the WorkflowStoreActor
[2018-05-23 17:05:40,82] [info] MaterializeWorkflowDescriptorActor [730729a9]: Call-to-Backend assignments: ga4ghMd5.md5 -> TES
[2018-05-23 17:05:43,04] [info] WorkflowExecutionActor-730729a9-5dbc-455f-84ee-cbcbbbf08b38 [730729a9]: Starting ga4ghMd5.md5
[2018-05-23 17:05:43,48] [info] TesAsyncBackendJobExecutionActor [730729a9ga4ghMd5.md5:NA:1]: /bin/my_md5sum /home/dyuen/ktesting/md5sum.input
[2018-05-23 17:05:43,67] [error] TesAsyncBackendJobExecutionActor [730729a9ga4ghMd5.md5:NA:1]: Error attempting to Execute
spray.json.DeserializationException: Object is missing required member 'id'
	at spray.json.package$.deserializationError(package.scala:23)
	at spray.json.ProductFormats.fromField(ProductFormats.scala:60)
	at spray.json.ProductFormats.fromField$(ProductFormats.scala:50)
	at cromwell.backend.impl.tes.TesResponseJsonFormatter$.fromField(TesResponseJsonFormatter.scala:9)
	at spray.json.ProductFormatsInstances$$anon$1.read(ProductFormatsInstances.scala:34)
	at spray.json.ProductFormatsInstances$$anon$1.read(ProductFormatsInstances.scala:26)
	at akka.http.scaladsl.marshallers.sprayjson.SprayJsonSupport.$anonfun$sprayJsonUnmarshaller$1(SprayJsonSupport.scala:30)
	at akka.http.scaladsl.util.FastFuture$.$anonfun$map$1(FastFuture.scala:23)
	at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
	at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45)
	at akka.http.scaladsl.util.FastFuture$.map$extension(FastFuture.scala:23)
	at akka.http.scaladsl.unmarshalling.Unmarshaller.$anonfun$map$3(Unmarshaller.scala:26)
	at akka.http.scaladsl.unmarshalling.Unmarshaller.$anonfun$transform$3(Unmarshaller.scala:23)
	at akka.http.scaladsl.unmarshalling.Unmarshaller$$anon$1.apply(Unmarshaller.scala:58)
	at akka.http.scaladsl.unmarshalling.Unmarshal.to(Unmarshal.scala:25)
	at cromwell.backend.impl.tes.TesAsyncBackendJobExecutionActor.$anonfun$makeRequest$1(TesAsyncBackendJobExecutionActor.scala:221)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:304)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: java.util.NoSuchElementException: key not found: id
	at scala.collection.MapLike.default(MapLike.scala:232)
	at scala.collection.MapLike.default$(MapLike.scala:231)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.MapLike.apply(MapLike.scala:141)
	at scala.collection.MapLike.apply$(MapLike.scala:140)
	at scala.collection.AbstractMap.apply(Map.scala:59)
	at spray.json.ProductFormats.fromField(ProductFormats.scala:57)
	... 28 common frames omitted
[2018-05-23 17:05:43,67] [warn] Couldn't find a suitable DSN, defaulting to a Noop one.
[2018-05-23 17:05:43,68] [info] Using noop to send events.
[2018-05-23 17:05:44,10] [error] WorkflowManagerActor Workflow 730729a9-5dbc-455f-84ee-cbcbbbf08b38 failed (during ExecutingWorkflowState): spray.json.DeserializationException: Object is missing required member 'id'
cromwell.core.CromwellFatalException: spray.json.DeserializationException: Object is missing required member 'id'
	at cromwell.core.CromwellFatalException$.apply(core.scala:18)
	at cromwell.core.retry.Retry$$anonfun$withRetry$1.applyOrElse(Retry.scala:38)
	at cromwell.core.retry.Retry$$anonfun$withRetry$1.applyOrElse(Retry.scala:37)
	at scala.concurrent.Future.$anonfun$recoverWith$1(Future.scala:414)
	at scala.concurrent.impl.Promise.$anonfun$transformWith$1(Promise.scala:37)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:43)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
Caused by: spray.json.DeserializationException: Object is missing required member 'id'
	at spray.json.package$.deserializationError(package.scala:23)
	at spray.json.ProductFormats.fromField(ProductFormats.scala:60)
	at spray.json.ProductFormats.fromField$(ProductFormats.scala:50)
	at cromwell.backend.impl.tes.TesResponseJsonFormatter$.fromField(TesResponseJsonFormatter.scala:9)
	at spray.json.ProductFormatsInstances$$anon$1.read(ProductFormatsInstances.scala:34)
	at spray.json.ProductFormatsInstances$$anon$1.read(ProductFormatsInstances.scala:26)
	at akka.http.scaladsl.marshallers.sprayjson.SprayJsonSupport.$anonfun$sprayJsonUnmarshaller$1(SprayJsonSupport.scala:30)
	at akka.http.scaladsl.util.FastFuture$.$anonfun$map$1(FastFuture.scala:23)
	at akka.http.scaladsl.util.FastFuture$.strictTransform$1(FastFuture.scala:41)
	at akka.http.scaladsl.util.FastFuture$.transformWith$extension1(FastFuture.scala:45)
	at akka.http.scaladsl.util.FastFuture$.map$extension(FastFuture.scala:23)
	at akka.http.scaladsl.unmarshalling.Unmarshaller.$anonfun$map$3(Unmarshaller.scala:26)
	at akka.http.scaladsl.unmarshalling.Unmarshaller.$anonfun$transform$3(Unmarshaller.scala:23)
	at akka.http.scaladsl.unmarshalling.Unmarshaller$$anon$1.apply(Unmarshaller.scala:58)
	at akka.http.scaladsl.unmarshalling.Unmarshal.to(Unmarshal.scala:25)
	at cromwell.backend.impl.tes.TesAsyncBackendJobExecutionActor.$anonfun$makeRequest$1(TesAsyncBackendJobExecutionActor.scala:221)
	at scala.concurrent.Future.$anonfun$flatMap$1(Future.scala:304)
	... 13 more
Caused by: java.util.NoSuchElementException: key not found: id
	at scala.collection.MapLike.default(MapLike.scala:232)
	at scala.collection.MapLike.default$(MapLike.scala:231)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.MapLike.apply(MapLike.scala:141)
	at scala.collection.MapLike.apply$(MapLike.scala:140)
	at scala.collection.AbstractMap.apply(Map.scala:59)
	at spray.json.ProductFormats.fromField(ProductFormats.scala:57)
	... 28 more

[2018-05-23 17:05:44,10] [info] WorkflowManagerActor WorkflowActor-730729a9-5dbc-455f-84ee-cbcbbbf08b38 is in a terminal state: WorkflowFailedState
[2018-05-23 17:05:47,84] [info] SingleWorkflowRunnerActor workflow finished with status 'Failed'.
```

Cromwell configured like 
```
    TES {
      actor-factory = "cromwell.backend.impl.tes.TesBackendLifecycleActorFactory"
      config {
        root = "cromwell-executions"
        dockerRoot = "/cromwell-executions"
        endpoint = "http://192.168.99.100:31196/v1/jobs"
        default-runtime-attributes {
          cpu: 1
          failOnStderr: false
          continueOnReturnCode: 0
          memory: "2 GB"
          disk: "2 GB"
        }
      }
    }

```

**Comment by denis-yuen** [comment]
Think there's a typo in the docs. 
Should be tasks not jobs (oh terminology). Now it hangs later, which is slightly better

```
$ java -Dconfig.file=cromwell.conf  -jar cromwell-31.1.jar run Dockstore.wdl  --inputs input.json [2018-05-24 11:05:45,76] [info] Running with database db.url = jdbc:hsqldb:mem:6e08466f-e644-4bed-926c-7b2f0b45ddb5;shutdown=false;hsqldb.tx=mvcc
[2018-05-24 11:05:50,09] [info] Running migration RenameWorkflowOptionsInMetadata with a read batch size of 100000 and a write batch size of 100000
[2018-05-24 11:05:50,10] [info] [RenameWorkflowOptionsInMetadata] 100%
[2018-05-24 11:05:50,17] [info] Running with database db.url = jdbc:hsqldb:mem:074ff2fc-2c46-4bb0-98d3-15fdb1e0510d;shutdown=false;hsqldb.tx=mvcc
[2018-05-24 11:05:50,42] [info] Slf4jLogger started
[2018-05-24 11:05:50,54] [info] Metadata summary refreshing every 2 seconds.
[2018-05-24 11:05:50,57] [info] WriteMetadataActor configured to flush with batch size 200 and process rate 5 seconds.
[2018-05-24 11:05:50,57] [info] KvWriteActor configured to flush with batch size 200 and process rate 5 seconds.
[2018-05-24 11:05:50,57] [info] CallCacheWriteActor configured to flush with batch size 100 and process rate 3 seconds.
[2018-05-24 11:05:51,02] [info] JobExecutionTokenDispenser - Distribution rate: 50 per 1 seconds.
[2018-05-24 11:05:51,04] [info] SingleWorkflowRunnerActor: Submitting workflow
[2018-05-24 11:05:51,07] [info] WDL (Unspecified version) workflow 21136a19-a12a-45c3-a46e-6ad072ecbadb submitted
[2018-05-24 11:05:51,08] [info] SingleWorkflowRunnerActor: Workflow submitted 21136a19-a12a-45c3-a46e-6ad072ecbadb
[2018-05-24 11:05:51,08] [info] 1 new workflows fetched
[2018-05-24 11:05:51,08] [info] WorkflowManagerActor Starting workflow 21136a19-a12a-45c3-a46e-6ad072ecbadb
[2018-05-24 11:05:51,08] [info] WorkflowManagerActor Successfully started WorkflowActor-21136a19-a12a-45c3-a46e-6ad072ecbadb
[2018-05-24 11:05:51,08] [info] Retrieved 1 workflows from the WorkflowStoreActor
[2018-05-24 11:05:51,72] [info] MaterializeWorkflowDescriptorActor [21136a19]: Call-to-Backend assignments: ga4ghMd5.md5 -> TES
[2018-05-24 11:05:53,93] [info] WorkflowExecutionActor-21136a19-a12a-45c3-a46e-6ad072ecbadb [21136a19]: Starting ga4ghMd5.md5
[2018-05-24 11:05:54,41] [info] TesAsyncBackendJobExecutionActor [21136a19ga4ghMd5.md5:NA:1]: /bin/my_md5sum /home/dyuen/ktesting/md5sum.input
[2018-05-24 11:05:55,61] [info] TesAsyncBackendJobExecutionActor [21136a19ga4ghMd5.md5:NA:1]: job id: task-e445299e
[2018-05-24 11:05:55,90] [info] TesAsyncBackendJobExecutionActor [21136a19ga4ghMd5.md5:NA:1]: Status change from - to Running

```

**Comment by denis-yuen** [comment]
Looks like https://github.com/ohsu-comp-bio/py-tes/commit/a7c64930883e70cfd8d01a48e41509bb6d5838e9 is needed

**Comment by denis-yuen** [comment]
Hacking that commit in, I get further ...
```
$ cwl-tes --tes http://192.168.99.100:31196 tests/hashsplitter-workflow.cwl.yml --input tests/resources/test.txt
/home/dyuen/cwl-tes/venv/bin/cwl-tes 0.2.0 with cwltool 1.0.20180108222053
Resolved 'tests/hashsplitter-workflow.cwl.yml' to 'file:///home/dyuen/cwl-tes/tests/hashsplitter-workflow.cwl.yml'
[workflow hashsplitter-workflow.cwl.yml] start
[step whirlpool] start
[job whirlpool] CREATED TASK MSG----------------------
Task(id=None, state=None, name='whirlpool', description='hash input through sha512', inputs=[Input(url='file:///home/dyuen/cwl-tes/tests/resources/test.txt', path='/var/lib/cwl/stg3765d087-12eb-48b5-be06-f44a7656
8050/test.txt', type='FILE', name='input', description='cwl_input:input', content=None)], outputs=[Output(url='file:///tmp/tmpqbOaKR/whirpool', path='/var/spool/cwl/whirpool', type=u'FILE', name='stdout', descrip
tion=None), Output(url='file:///tmp/tmpqbOaKR/', path='/var/spool/cwl', type=u'DIRECTORY', name='workdir', description=None)], resources=Resources(cpu_cores=None, ram_gb=None, disk_gb=None, preemptible=None, zone
s=None), executors=[Executor(image='openssl', command=['openssl', 'dgst', '-sha512', '/var/lib/cwl/stg3765d087-12eb-48b5-be06-f44a76568050/test.txt'], workdir='/var/spool/cwl', stdin=None, stdout='/var/spool/cwl/
whirpool', stderr=None, env={})], volumes=None, tags={u'CWLDocumentId': 'file:///home/dyuen/cwl-tes/tests/hashsplitter-whirlpool.cwl.yml'}, logs=None, creation_time=None)
[job whirlpool] SUBMITTED TASK ----------------------
[job whirlpool] task id: task-29e19bf2 
[step md5] start
[job md5] CREATED TASK MSG----------------------
Task(id=None, state=None, name='md5', description='hash input through md5', inputs=[Input(url='file:///home/dyuen/cwl-tes/tests/resources/test.txt', path='/var/lib/cwl/stg3ad990ee-2c3d-45a2-8aed-9dd5fa2f79bd/test
.txt', type='FILE', name='input', description='cwl_input:input', content=None)], outputs=[Output(url='file:///tmp/tmpUVGNS8/md5', path='/var/spool/cwl/md5', type=u'FILE', name='stdout', description=None), Output(
url='file:///tmp/tmpUVGNS8/', path='/var/spool/cwl', type=u'DIRECTORY', name='workdir', description=None)], resources=Resources(cpu_cores=None, ram_gb=None, disk_gb=None, preemptible=None, zones=None), executors=
[Executor(image='openssl', command=['openssl', 'dgst', '-md5', '/var/lib/cwl/stg3ad990ee-2c3d-45a2-8aed-9dd5fa2f79bd/test.txt'], workdir='/var/spool/cwl', stdin=None, stdout='/var/spool/cwl/md5', stderr=None, env
={})], volumes=None, tags={u'CWLDocumentId': 'file:///home/dyuen/cwl-tes/tests/hashsplitter-md5.cwl.yml'}, logs=None, creation_time=None)
[job md5] SUBMITTED TASK ----------------------
[job md5] task id: task-4a5a5cc9 
[step sha] start
[job sha] CREATED TASK MSG----------------------
Task(id=None, state=None, name='sha', description='hash input through sha', inputs=[Input(url='file:///home/dyuen/cwl-tes/tests/resources/test.txt', path='/var/lib/cwl/stg3829e985-14d0-450e-8d0d-886980a1fa34/test
.txt', type='FILE', name='input', description='cwl_input:input', content=None)], outputs=[Output(url='file:///tmp/tmpc0MGws/sha', path='/var/spool/cwl/sha', type=u'FILE', name='stdout', description=None), Output(
url='file:///tmp/tmpc0MGws/', path='/var/spool/cwl', type=u'DIRECTORY', name='workdir', description=None)], resources=Resources(cpu_cores=None, ram_gb=None, disk_gb=None, preemptible=None, zones=None), executors=
[Executor(image='openssl', command=['openssl', 'dgst', '-sha', '/var/lib/cwl/stg3829e985-14d0-450e-8d0d-886980a1fa34/test.txt'], workdir='/var/spool/cwl', stdin=None, stdout='/var/spool/cwl/sha', stderr=None, env
={})], volumes=None, tags={u'CWLDocumentId': 'file:///home/dyuen/cwl-tes/tests/hashsplitter-sha.cwl.yml'}, logs=None, creation_time=None)
[job sha] SUBMITTED TASK ----------------------
[job sha] task id: task-5dd7d690 
[job whirlpool] FINAL JOB STATE: SYSTEM_ERROR ------------------
[job whirlpool] task id: task-29e19bf2
[job sha] FINAL JOB STATE: SYSTEM_ERROR ------------------
[job sha] task id: task-5dd7d690
[job md5] POLLING ERROR HTTPConnectionPool(host='192.168.99.100', port=31196): Read timed out. (read timeout=10)
Exception in thread whirlpool:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "build/bdist.linux-x86_64/egg/cwl_tes/tes.py", line 460, in run
    while not self.is_done(self.state):
  File "build/bdist.linux-x86_64/egg/cwl_tes/tes.py", line 503, in is_done
    self.client.get_task(self.id, "FULL").logs
  File "/home/dyuen/cwl-tes/venv/local/lib/python2.7/site-packages/tes/client.py", line 62, in get_task
    timeout=self.timeout

```

**Comment by denis-yuen** [comment]
ok, restarting minikube with more memory and cores seemed to help a bit. 
Now tasks seem to start properly and I can get into the minikube dashboard to see a pile of " pod has unbound PersistentVolumeClaims "

**Comment by denis-yuen** [comment]
Useful commands:
minikube start
kubectl create -f .
minikube service tesk-api --url
curl  -X POST  -s  --header 'Content-Type: application/json'  --header 'Accept: application/json'  -d @../../examples/success/stdout.json  'http://192.168.99.100:31196/v1/tasks'
kubectl dashboard
(cwl-tes)
virtualenv venv
