### ISSUE TITLE
DOS File Provisioner Plugin Breaks Older Versions of Dockstore CLI

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1629]
## Bug Report

If DOS File Provisioner plugin gets installed as part of Dockstore 1.5, and then you go back to Dockstore 1.4, Dockstore 1.4 CLI will no longer run.

The DOS File Provisioner implements a `PreProvisionInterface` that only exists in dockstore-file-plugin-parent 1.5. When running Dockstore 1.4, the interface definition doesn't exist, and the plugin fails to load with a `ClassNotFoundException`, and the client exits:

```
~$ dockstore plugin list
Exception in thread "main" java.lang.NoClassDefFoundError: io/dockstore/provision/PreProvisionInterface
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at ro.fortsoft.pf4j.PluginClassLoader.loadClass(PluginClassLoader.java:85)
	at ro.fortsoft.pf4j.AbstractExtensionFinder.find(AbstractExtensionFinder.java:100)
	at ro.fortsoft.pf4j.DefaultExtensionFinder.find(DefaultExtensionFinder.java:57)
	at ro.fortsoft.pf4j.DefaultPluginManager.getExtensions(DefaultPluginManager.java:566)
	at io.dockstore.client.cli.PluginClient.handleList(PluginClient.java:122)
	at io.dockstore.client.cli.PluginClient.handleCommand(PluginClient.java:88)
	at io.dockstore.client.cli.Client.run(Client.java:683)
	at io.dockstore.client.cli.Client.main(Client.java:606)
Caused by: java.lang.ClassNotFoundException: io.dockstore.provision.PreProvisionInterface
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at ro.fortsoft.pf4j.PluginClassLoader.loadClass(PluginClassLoader.java:107)
	... 17 more
```

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DOCK-52)
┆Sprint: Lighthouse Sprint 31 Eblis
┆Issue Number: DOCK-52
┆Epic: DOS File Provisioner

**Comment by denis-yuen** [comment]
Oh crud, I probably understood this incorrectly. My thought was that 1.5 Dockstore was being broken by older plugins that don't implement the interface. My idea about interface default implementations would address that. 

In this case, a new 1.5 style plugin is breaking 1.4 Dockstore, so we can't really change it on the 1.4 side. I think we might be hooped with the workaround being to delete the new plugin. 
We should, however, make Dockstore ignore plugins it can't load more gracefully so that would stop future problems.

**Comment by coverbeck** [comment]
Yeah, I didn't explain this properly at the meeting. Walt had shown me the error, but I hadn't looked into the details until I wrote this up, which is when I realized your solution wouldn't work.

I was hoping there was something fancy I could do in the plugin itself, although looking at the code I'm not optimistic.

**Comment by coverbeck** [comment]
One possible solution, untested:

* Download new plugins to plugins2
* Older version of Dockstore would only read plugins directory.
* Dockstore 1.5 also reads plugins2 directory

This would require changes to the dockstore script.

I think this would be a bit of work. Is it worth going this route?

The lame solution is just to tell people, somehow, to delete the DOS plugin.

There may be other solutions, this is just what I thought of off-hand.

**Comment by denis-yuen** [comment]
I'm thinking that the number of people downgrading should be small enough that that the untested solution seems overkill.

**Comment by denis-yuen** [comment]
`dockstore plugin list` from 1.4.4 seems to ignore old plugin correctly.
