### ISSUE TITLE
Google check too verbose

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1817]
### Expected behaviour

someone using an invalid google token should result in a one-liner log message

### Actual behaviour

Stacktrace occurs too often. Stack trace can be DEBUG while the message itself can remain INFO

```
ebservice_1     | INFO  [2018-09-12 20:11:15,523] io.dockstore.webservice.helpers.GoogleHelper: Error getting token info
webservice_1     | ! java.lang.IllegalArgumentException: expected primitive class, but got: class com.google.api.client.googleapis.json.GoogleJsonError
webservice_1     | ! at com.google.api.client.util.Data.parsePrimitiveValue(Data.java:453)
webservice_1     | ! at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:859)
webservice_1     | ! ... 98 common frames omitted
webservice_1     | ! Causing: java.lang.IllegalArgumentException: key error
```

https://github.com/ga4gh/dockstore/blob/develop/dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/GoogleHelper.java#L158

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DOCK-82)
┆Issue Number: DOCK-82

**Comment by denis-yuen** [comment]
Seems fixed on the webservice log side of things (with non-logged in users)

**Comment by denis-yuen** [comment]
```
webservice_1     | WARN  [2018-09-14 18:01:10,904] com.google.api.client.googleapis.services.AbstractGoogleClient: Application name is not set. Call Builder#setApplicationName.
webservice_1     | INFO  [2018-09-14 18:01:10,991] io.dockstore.webservice.helpers.GoogleHelper: Error getting token info: key error
```

Much quieter on staging
