### ISSUE TITLE
Dockstore CLI Fails Launching a WDL with Imports

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1847]
## Bug Report

The following checker workflow has WDL imports. You get an NPE when you try to launch it:

```
dockstore workflow launch --entry github.com/DataBiosphere/topmed-workflows/u_of_Michigan_alignment_pipeline_wdl_checker:1.29.0 --json foo.json
15:15:23.562 [main] ERROR io.dockstore.client.cli.ArgumentUtility - Could not get WDL imports: null
15:15:23.567 [main] ERROR io.dockstore.client.cli.ArgumentUtility - java.lang.NullPointerException
	at wdl4s.wdl.WdlNamespace$.apply(WdlNamespace.scala:216)
	at wdl4s.wdl.WdlNamespace$$anonfun$wdl4s$wdl$WdlNamespace$$load$1.apply(WdlNamespace.scala:179)
	at wdl4s.wdl.WdlNamespace$$anonfun$wdl4s$wdl$WdlNamespace$$load$1.apply(WdlNamespace.scala:179)
	at scala.util.Try$.apply(Try.scala:192)
	at wdl4s.wdl.WdlNamespace$.wdl4s$wdl$WdlNamespace$$load(WdlNamespace.scala:178)
	at wdl4s.wdl.WdlNamespace$$anonfun$20.apply(WdlNamespace.scala:209)
	at wdl4s.wdl.WdlNamespace$$anonfun$20.apply(WdlNamespace.scala:207)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.List.foreach(List.scala:392)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.immutable.List.map(List.scala:296)
	at wdl4s.wdl.WdlNamespace$.apply(WdlNamespace.scala:207)
	at wdl4s.wdl.WdlNamespace$$anonfun$wdl4s$wdl$WdlNamespace$$load$1.apply(WdlNamespace.scala:179)
	at wdl4s.wdl.WdlNamespace$$anonfun$wdl4s$wdl$WdlNamespace$$load$1.apply(WdlNamespace.scala:179)
	at scala.util.Try$.apply(Try.scala:192)
	at wdl4s.wdl.WdlNamespace$.wdl4s$wdl$WdlNamespace$$load(WdlNamespace.scala:178)
	at wdl4s.wdl.WdlNamespace$.loadUsingSource(WdlNamespace.scala:175)
	at wdl4s.wdl.WdlNamespaceWithWorkflow$.load(WdlNamespace.scala:555)
	at io.dockstore.common.Bridge.getInputFiles(Bridge.scala:91)
	at io.github.collaboratory.wdl.WDLClient.launch(WDLClient.java:151)
	at io.dockstore.client.cli.nested.WorkflowClient.launch(WorkflowClient.java:436)
	at io.dockstore.client.cli.nested.AbstractEntryClient.processEntryCommands(AbstractEntryClient.java:226)
	at io.dockstore.client.cli.Client.run(Client.java:706)
	at io.dockstore.client.cli.Client.main(Client.java:608)```

```
Here is the foo.json, used as an input:
```
 "checkerWorkflow.input_cram_file": "https://storage.googleapis.com/topmed_workflow_testing/topmed_aligner/input_files/NWD176325.25reads.cram",
"checkerWorkflow.input_crai_file": "https://storage.googleapis.com/topmed_workflow_testing/topmed_aligner/input_files/NWD176325.25reads.cram.crai",
  "checkerWorkflow.inputTruthCRAMFile": "https://storage.googleapis.com/topmed_workflow_testing/topmed_aligner_checker/truth_NWD176325.25reads.cram",
  "checkerWorkflow.ref_alt":  "https://storage.googleapis.com/topmed_workflow_testing/topmed_aligner/reference_files/hg38/hs38DH.fa.alt",
  "checkerWorkflow.ref_bwt":  "https://storage.googleapis.com/topmed_workflow_testing/topmed_aligner/reference_files/hg38/hs38DH.fa.bwt",
  "checkerWorkflow.ref_pac":  "https://storage.googleapis.com/topmed_workflow_testing/topmed_aligner/reference_files/hg38/hs38DH.fa.pac",
  "checkerWorkflow.ref_ann":  "https://storage.googleapis.com/topmed_workflow_testing/topmed_aligner/reference_files/hg38/hs38DH.fa.ann",
  "checkerWorkflow.ref_amb":  "https://storage.googleapis.com/topmed_workflow_testing/topmed_aligner/reference_files/hg38/hs38DH.fa.amb",
  "checkerWorkflow.ref_sa":  "https://storage.googleapis.com/topmed_workflow_testing/topmed_aligner/reference_files/hg38/hs38DH.fa.sa",
  "checkerWorkflow.ref_fasta":  "https://storage.googleapis.com/topmed_workflow_testing/topmed_aligner/reference_files/hg38/hs38DH.fa",
  "checkerWorkflow.ref_fasta_index":  "https://storage.googleapis.com/topmed_workflow_testing/topmed_aligner/reference_files/hg38/hs38DH.fa.fai",
  "checkerWorkflow.dbSNP_vcf": "https://storage.googleapis.com/topmed_workflow_testing/topmed_aligner/reference_files/hg38/Homo_sapiens_assembly38.dbsnp138.vcf.gz",
  "checkerWorkflow.dbSNP_vcf_index": "https://storage.googleapis.com/topmed_workflow_testing/topmed_aligner/reference_files/hg38/Homo_sapiens_assembly38.dbsnp138.vcf.gz.tbi",
  "checkerWorkflow.docker_image": "statgen/alignment:1.0.0"
}```

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DOCK-95)
┆Issue Number: DOCK-95

**Comment by denis-yuen** [comment]
To confirm (feeling a bit light-headed), this affects our CLI launching workflows but not other platforms launching these workflows because those http imports are not being indexed anyway by us

**Comment by denis-yuen** [comment]
Hmmm, but is it grabbing the code for launching on the command-line or is it grabbing it for the purposes of import? The latter would be more serious

**Comment by coverbeck** [comment]
My reading is that it is trying to parse the WDL so it can determine the inputs for the command-line launch. Not sure if that's answering your question or not.

**Comment by coverbeck** [comment]
I don't see the imported files at https://dockstore.org/workflows/github.com/DataBiosphere/topmed-workflows/u_of_Michigan_alignment_pipeline:1.30.0?tab=files. So it looks like they are not in the database.

**Comment by denis-yuen** [comment]
Oh, I see what I'm missing. They're http(s) imports, ignore what I said about 2).

**Comment by garyluu** [comment]
Files downloaded and then:
```
Calling out to Cromwell to run your workflow
java -jar /home/gluu/.dockstore/libraries/cromwell-30.2.jar run /tmp/1543861994963-0/aligner/u_of_michigan_aligner-checker/u_of_michigan_aligner_checker.wdl --inputs /tmp/foo2536991570141326724json
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.access$200(DefaultExecutor.java:48)
	at org.apache.commons.exec.DefaultExecutor$1.run(DefaultExecutor.java:200)
	at java.lang.Thread.run(Thread.java:748)
13:42:03.738 [main] ERROR io.github.collaboratory.wdl.WDLClient - Problem running cromwell: 
java.lang.RuntimeException: problems running command: java -jar /home/gluu/.dockstore/libraries/cromwell-30.2.jar run /tmp/1543861994963-0/aligner/u_of_michigan_aligner-checker/u_of_michigan_aligner_checker.wdl --inputs /tmp/foo2536991570141326724json
	at io.dockstore.common.Utilities.executeCommand(Utilities.java:142)
	at io.dockstore.common.Utilities.executeCommand(Utilities.java:88)
	at io.github.collaboratory.wdl.WDLClient.launch(WDLClient.java:203)
	at io.dockstore.client.cli.nested.WorkflowClient.launch(WorkflowClient.java:436)
	at io.dockstore.client.cli.nested.AbstractEntryClient.processEntryCommands(AbstractEntryClient.java:226)
	at io.dockstore.client.cli.Client.run(Client.java:706)
	at io.dockstore.client.cli.Client.main(Client.java:608)
Caused by: org.apache.commons.exec.ExecuteException: problems running command: java -jar /home/gluu/.dockstore/libraries/cromwell-30.2.jar run /tmp/1543861994963-0/aligner/u_of_michigan_aligner-checker/u_of_michigan_aligner_checker.wdl --inputs /tmp/foo2536991570141326724json (Exit value: 1)
	at io.dockstore.common.Utilities.executeCommand(Utilities.java:138)
	... 6 common frames omitted
Cromwell exit code: 1
13:42:03.745 [main] ERROR io.dockstore.client.cli.ArgumentUtility - org.apache.commons.exec.ExecuteException: problems running command: java -jar /home/gluu/.dockstore/libraries/cromwell-30.2.jar run /tmp/1543861994963-0/aligner/u_of_michigan_aligner-checker/u_of_michigan_aligner_checker.wdl --inputs /tmp/foo2536991570141326724json (Exit value: 1)
	at io.github.collaboratory.wdl.WDLClient.launch(WDLClient.java:210)
	at io.dockstore.client.cli.nested.WorkflowClient.launch(WorkflowClient.java:436)
	at io.dockstore.client.cli.nested.AbstractEntryClient.processEntryCommands(AbstractEntryClient.java:226)
	at io.dockstore.client.cli.Client.run(Client.java:706)
	at io.dockstore.client.cli.Client.main(Client.java:608)
```

**Comment by denis-yuen** [comment]
I think it is suppressing the real output. What happens when you just run "java -jar /home/gluu/.dockstore/libraries/cromwell-30.2.jar run /tmp/1543861994963-0/aligner/u_of_michigan_aligner-checker/u_of_michigan_aligner_checker.wdl --inputs /tmp/foo2536991570141326724json"?

**Comment by coverbeck** [comment]
Are you running on a Mac? There is an issue at the very end where the md5sum on a Mac fails for that workflow (but it gets past the original error reported by this ticket). The problem is that the output of md5um on a Mac varies from that of Linux -- there is additional path info.

**Comment by garyluu** [comment]
Running on Ubuntu:
```
2018-12-03 14:21:28,86] [error] WorkflowManagerActor Workflow ac8273b0-e91c-48ac-91f8-c0cc605b0861 failed (during ExecutingWorkflowState): Call input and runtime attributes evaluation failed for checkerTask:
No coercion defined from '200' of type 'Int' to 'Float'.
cromwell.engine.workflow.lifecycle.execution.job.preparation.JobPreparationActor$$anonfun$1$$anon$1: Call input and runtime attributes evaluation failed for checkerTask:
No coercion defined from '200' of type 'Int' to 'Float'.
	at cromwell.engine.workflow.lifecycle.execution.job.preparation.JobPreparationActor$$anonfun$1.applyOrElse(JobPreparationActor.scala:62)
	at cromwell.engine.workflow.lifecycle.execution.job.preparation.JobPreparationActor$$anonfun$1.applyOrElse(JobPreparationActor.scala:58)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:34)
	at akka.actor.FSM.processEvent(FSM.scala:665)
	at akka.actor.FSM.processEvent$(FSM.scala:662)
	at cromwell.engine.workflow.lifecycle.execution.job.preparation.JobPreparationActor.processEvent(JobPreparationActor.scala:37)
	at akka.actor.FSM.akka$actor$FSM$$processMsg(FSM.scala:659)
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:653)
	at akka.actor.Actor.aroundReceive(Actor.scala:514)
	at akka.actor.Actor.aroundReceive$(Actor.scala:512)
	at cromwell.engine.workflow.lifecycle.execution.job.preparation.JobPreparationActor.aroundReceive(JobPreparationActor.scala:37)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527)
	at akka.actor.ActorCell.invoke(ActorCell.scala:496)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

[2018-12-03 14:21:28,86] [info] WorkflowManagerActor WorkflowActor-ac8273b0-e91c-48ac-91f8-c0cc605b0861 is in a terminal state: WorkflowFailedState
[2018-12-03 14:21:56,17] [info] SingleWorkflowRunnerActor workflow finished with status 'Failed'.
[2018-12-03 14:21:56,19] [info] Message [cromwell.core.actor.StreamActorHelper$StreamFailed] without sender to Actor[akka://cromwell-system/deadLetters] was not delivered. [1] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[2018-12-03 14:21:56,19] [info] Message [cromwell.core.actor.StreamActorHelper$StreamFailed] without sender to Actor[akka://cromwell-system/deadLetters] was not delivered. [2] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
Workflow ac8273b0-e91c-48ac-91f8-c0cc605b0861 transitioned to state Failed
[2018-12-03 14:21:56,24] [info] Automatic shutdown of the async connection
[2018-12-03 14:21:56,24] [info] Gracefully shutdown sentry threads.
[2018-12-03 14:21:56,24] [info] Shutdown finished.
```

**Comment by coverbeck** [comment]
cc: @wshands 

I think this workflow doesn't work with Cromwell 30.2. I think I ran it successfully with Cromwell 36. Will try later today. Sorry for the confusion.

**Comment by coverbeck** [comment]
Verified this with staging, using Cromwell 36.

My ~/.dockstore/config settings:

```
server-url: https://staging.dockstore.org/api
cromwell-version: 36
```

And I did an `EXPORT DOCKSTORE_VERSION=1.5.3`

The workflow failed at the very end, running on a Mac, due to a known problem with the workflow that Walt is going to look into, but it is unrelated to the provisioning that this bug fixes. Here's the output when running the Java program:

```
[2018-12-05 11:51:14,99] [info] BackgroundConfigAsyncJobExecutionActor [abbd26efcheckerWorkflow.checkerTask:NA:1]: job id: 70032
[2018-12-05 11:51:15,00] [info] BackgroundConfigAsyncJobExecutionActor [abbd26efcheckerWorkflow.checkerTask:NA:1]: Status change from - to WaitingForReturnCode
[2018-12-05 11:52:48,39] [info] BackgroundConfigAsyncJobExecutionActor [abbd26efcheckerWorkflow.checkerTask:NA:1]: Status change from WaitingForReturnCode to Done
[2018-12-05 11:52:49,37] [error] WorkflowManagerActor Workflow abbd26ef-a445-48ec-b1e5-6b6a19604a61 failed (during ExecutingWorkflowState): Job checkerWorkflow.checkerTask:NA:1 exited with return code 1 which has not been declared as a valid return code. See 'continueOnReturnCode' runtime attribute for more details.
Check the content of stderr for potential additional information: /Users/charlesoverbeck/tmp/cromwell-executions/checkerWorkflow/abbd26ef-a445-48ec-b1e5-6b6a19604a61/call-checkerTask/execution/stderr.
 [samfaipath] build FASTA index...
md5sum: WARNING: 1 computed checksum did NOT match
```
