### ISSUE TITLE
Dockstore may not correctly handle expired Google refresh tokens

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1945]
## Bug Report

On staging, I was seeing 401 errors fetching shared workflows on the My Workflows page.

After I unlinked and relinked my Google account, the error went away.

Before unlinking, I noticed these errors in the log:

```
 ERROR [2018-12-04 23:23:29,994] io.dockstore.webservice.helpers.GoogleHelper: Error refreshing token
  com.google.api.client.auth.oauth2.TokenResponseException: 401 Unauthorized
  {
    "error" : "unauthorized_client",
    "error_description" : "Unauthorized"
  }
  at com.google.api.client.auth.oauth2.TokenResponseException.from(TokenResponseException.java:105)
  at com.google.api.client.auth.oauth2.TokenRequest.executeUnparsed(TokenRequest.java:287)
  at com.google.api.client.auth.oauth2.TokenRequest.execute(TokenRequest.java:307)
  at com.google.api.client.auth.oauth2.Credential.executeRefreshToken(Credential.java:570)
  at com.google.api.client.googleapis.auth.oauth2.GoogleCredential.executeRefreshToken(GoogleCredential.java:362)
  at com.google.api.client.auth.oauth2.Credential.refreshToken(Credential.java:489)
  at io.dockstore.webservice.helpers.GoogleHelper.lambda$getValidAccessToken$2(GoogleHelper.java:113)
  at java.util.Optional.orElseGet(Optional.java:267)
  at io.dockstore.webservice.helpers.GoogleHelper.getValidAccessToken(GoogleHelper.java:103)
  at io.dockstore.webservice.permissions.sam.SamPermissionsImpl.googleAccessToken(SamPermissionsImpl
```

My theory is that the Google refresh token expired, although I'm not 100% sure of that. I do know that Google refresh tokens expire.

If so, user should somehow be informed that their refresh token has expired and prompted to enter their credentials again.

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-294)
┆Issue Type: Bug
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 6 Ferry
┆Issue Number: DOCK-294

**Comment by david4096** [comment]
I was able to observe the improved error message by creating an account using google login and then revoking access in Google account settings https://myaccount.google.com/permissions .

DockstoreAPI - 1.6.0-beta.3 DockstoreUI - 2.3.0-beta.2
staging.dockstore.org
