### ISSUE TITLE
Migrations failing with latest data

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#2093]
## Bug Report

On develop branch, migrations is failing with the latest data, from Feb 6.

The code that is supposed to remove null values in a column before adding the not null constraint does seem to execute. Or perhaps it's in a different transaction.

Happened for both @Ldcabansay and me.

```
java -jar $WS_JAR db migrate ~/.dockstore/dockstore.yml  --include 1.5.0,1.6.0
...
INFO  [2019-02-07 22:22:58,546] liquibase.lockservice.StandardLockService: Successfully released change log lock
liquibase.exception.MigrationFailedException: Migration failed for change set migrations.1.6.0.xml::AddNotNullAbsolutePathConstraint::coverbeck:
     Reason: liquibase.exception.DatabaseException: ERROR: column "absolutepath" contains null values [Failed SQL: ALTER TABLE public.sourcefile ALTER COLUMN  absolutepath SET NOT NULL]
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:637)
	at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:53)
	at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:78)
	at liquibase.Liquibase.update(Liquibase.java:202)
	at liquibase.Liquibase.update(Liquibase.java:179)
	at liquibase.Liquibase.update(Liquibase.java:175)
	at liquibase.Liquibase.update(Liquibase.java:168)
	at io.dropwizard.migrations.DbMigrateCommand.run(DbMigrateCommand.java:68)
	at io.dropwizard.migrations.DbCommand.run(DbCommand.java:55)
	at io.dropwizard.migrations.AbstractLiquibaseCommand.run(AbstractLiquibaseCommand.java:68)
	at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
	at io.dropwizard.cli.Cli.run(Cli.java:78)
	at io.dropwizard.Application.run(Application.java:93)
	at io.dockstore.webservice.DockstoreWebserviceApplication.main(DockstoreWebserviceApplication.java:139)
Caused by: liquibase.exception.DatabaseException: ERROR: column "absolutepath" contains null values [Failed SQL: ALTER TABLE public.sourcefile ALTER COLUMN  absolutepath SET NOT NULL]
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:356)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:57)
	at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:125)
	at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1229)
	at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1211)
	at liquibase.changelog.ChangeSet.execute(ChangeSet.java:600)
	... 13 more
Caused by: org.postgresql.util.PSQLException: ERROR: column "absolutepath" contains null values
	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2190)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:301)
	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:287)
	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:264)
	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:260)
	at sun.reflect.GeneratedMethodAccessor284.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
	at com.sun.proxy.$Proxy32.execute(Unknown Source)
	at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:352)
	... 18 more
```

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-243)
┆Issue Type: Bug
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 5 Electric
┆Issue Number: DOCK-243

**Comment by Ldcabansay** [comment]
verified that running migrations now works without null value error
