### ISSUE TITLE
Refreshing a particular workflow in staging/local build fails

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#2139]
## Bug Report

Refreshing the workflow at `http://localhost:4200/my-workflows/github.com/DataBiosphere/topmed-workflows/TopMed_Variant_Caller` fails.

This fails because this [code](https://github.com/ga4gh/dockstore/blob/186af380240a570cbf37cc12d71ff85077e50e4e/dockstore-webservice/src/main/java/io/dockstore/webservice/languages/WDLHandler.java#L257) throws a CustomWebApplicationException.

1. Ideally the actual exception should be fixed.
2. Perhaps shouldn't throw an CustomWebApplicationException here if some other unexpected exception gets thrown, because it causes the refresh code to break.

It gets there through here:

```
 at io.dockstore.webservice.languages.WDLHandler.validateEntrySet(WDLHandler.java:257)
	  at io.dockstore.webservice.languages.WDLHandler.validateWorkflowSet(WDLHandler.java:270)
	  at io.dockstore.webservice.helpers.SourceCodeRepoInterface.versionValidation(SourceCodeRepoInterface.java:551)
	  at io.dockstore.webservice.helpers.GitHubSourceCodeRepo.setupWorkflowVersions(GitHubSourceCodeRepo.java:380)
	  at io.dockstore.webservice.helpers.SourceCodeRepoInterface.getWorkflow(SourceCodeRepoInterface.java:201)
	  at io.dockstore.webservice.resources.WorkflowResource.refresh(WorkflowResource.java:374)
```
The exception that is caught is a NoSuchMethodException:

```
java.lang.NoSuchMethodException: wdl4s.wdl.expression.WdlStandardLibraryFunctionsType.flatten(scala.collection.Seq)
0 = {StackTraceElement@11139} "java.lang.Class.getMethod(Class.java:1786)"
1 = {StackTraceElement@11140} "wdl4s.wdl.expression.WdlFunctions$class.getFunction(WdlFunctions.scala:10)"
2 = {StackTraceElement@11141} "wdl4s.wdl.expression.WdlStandardLibraryFunctionsType.getFunction(WdlStandardLibraryFunctions.scala:331)"
3 = {StackTraceElement@11142} "wdl4s.wdl.expression.TypeEvaluator.evaluate(TypeEvaluator.scala:113)"
4 = {StackTraceElement@11143} "wdl4s.wdl.WdlExpression$.evaluateType(WdlExpression.scala:91)"
5 = {StackTraceElement@11144} "wdl4s.wdl.WdlExpression.evaluateType(WdlExpression.scala:172)"
6 = {StackTraceElement@11145} "wdl4s.wdl.WdlNamespace$$anonfun$typeCheckDeclaration$1.apply(WdlNamespace.scala:451)"
7 = {StackTraceElement@11146} "wdl4s.wdl.WdlNamespace$$anonfun$typeCheckDeclaration$1.apply(WdlNamespace.scala:450)"
8 = {StackTraceElement@11147} "scala.Option.flatMap(Option.scala:171)"
9 = {StackTraceElement@11148} "wdl4s.wdl.WdlNamespace$.typeCheckDeclaration(WdlNamespace.scala:450)"
10 = {StackTraceElement@11149} "wdl4s.wdl.WdlNamespace$.validateDeclaration(WdlNamespace.scala:430)"
11 = {StackTraceElement@11150} "wdl4s.wdl.WdlNamespace$$anonfun$35$$anonfun$apply$16.apply(WdlNamespace.scala:345)"
12 = {StackTraceElement@11151} "wdl4s.wdl.WdlNamespace$$anonfun$35$$anonfun$apply$16.apply(WdlNamespace.scala:344)"
13 = {StackTraceElement@11152} "scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)"
14 = {StackTraceElement@11153} "scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)"
15 = {StackTraceElement@11154} "scala.collection.Iterator$class.foreach(Iterator.scala:891)"
16 = {StackTraceElement@11155} "scala.collection.AbstractIterator.foreach(Iterator.scala:1334)"
17 = {StackTraceElement@11156} "scala.collection.IterableLike$class.foreach(IterableLike.scala:72)"
18 = {StackTraceElement@11157} "scala.collection.AbstractIterable.foreach(Iterable.scala:54)"
19 = {StackTraceElement@11158} "scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)"
20 = {StackTraceElement@11159} "scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)"
21 = {StackTraceElement@11160} "wdl4s.wdl.WdlNamespace$$anonfun$35.apply(WdlNamespace.scala:344)"
22 = {StackTraceElement@11161} "wdl4s.wdl.WdlNamespace$$anonfun$35.apply(WdlNamespace.scala:343)"
23 = {StackTraceElement@11162} "scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)"
24 = {StackTraceElement@11163} "scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)"
25 = {StackTraceElement@11164} "scala.collection.immutable.HashSet$HashSet1.foreach(HashSet.scala:316)"
26 = {StackTraceElement@11165} "scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:972)"
27 = {StackTraceElement@11166} "scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:972)"
28 = {StackTraceElement@11167} "scala.collection.immutable.HashSet$HashTrieSet.foreach(HashSet.scala:972)"
29 = {StackTraceElement@11168} "scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)"
30 = {StackTraceElement@11169} "scala.collection.AbstractTraversable.flatMap(Traversable.scala:104)"
31 = {StackTraceElement@11170} "wdl4s.wdl.WdlNamespace$.apply(WdlNamespace.scala:343)"
32 = {StackTraceElement@11171} "wdl4s.wdl.WdlNamespace$$anonfun$wdl4s$wdl$WdlNamespace$$load$1.apply(WdlNamespace.scala:179)"
33 = {StackTraceElement@11172} "wdl4s.wdl.WdlNamespace$$anonfun$wdl4s$wdl$WdlNamespace$$load$1.apply(WdlNamespace.scala:179)"
34 = {StackTraceElement@11173} "scala.util.Try$.apply(Try.scala:192)"
35 = {StackTraceElement@11174} "wdl4s.wdl.WdlNamespace$.wdl4s$wdl$WdlNamespace$$load(WdlNamespace.scala:178)"
36 = {StackTraceElement@11175} "wdl4s.wdl.WdlNamespace$.loadUsingSource(WdlNamespace.scala:175)"
37 = {StackTraceElement@11176} "wdl4s.wdl.WdlNamespaceWithWorkflow$.load(WdlNamespace.scala:555)"
38 = {StackTraceElement@11177} "io.dockstore.common.Bridge.isValidWorkflow(Bridge.scala:98)"
39 = {StackTraceElement@11178} "io.dockstore.webservice.languages.WDLHandler.validateEntrySet(WDLHandler.java:251)"
40 = {StackTraceElement@11179} "io.dockstore.webservice.languages.WDLHandler.validateWorkflowSet(WDLHandler.java:270)"
41 = {StackTraceElement@11180} "io.dockstore.webservice.helpers.SourceCodeRepoInterface.versionValidation(SourceCodeRepoInterface.java:551)"
42 = {StackTraceElement@11181} "io.dockstore.webservice.helpers.GitHubSourceCodeRepo.setupWorkflowVersions(GitHubSourceCodeRepo.java:380)"
43 = {StackTraceElement@11182} "io.dockstore.webservice.helpers.SourceCodeRepoInterface.getWorkflow(SourceCodeRepoInterface.java:201)"
44 = {StackTraceElement@11183} "io.dockstore.webservice.resources.WorkflowResource.refresh(WorkflowResource.java:374)"
```

### Steps to reproduce the behaviour 

1. In local UI, assuming you belong to DataBiosphere GitHub org, goto `http://localhost:4200/my-workflows/github.com/DataBiosphere/topmed-workflows/TopMed_Variant_Caller`, and click the refresh button.
2. After a short delay, an error message is displayed.

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-533)
┆Issue Type: Bug
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 6 Ferry
┆Issue Number: DOCK-533

**Comment by coverbeck** [comment]
Note: this was failing on the add_metadata branch when I debugged it, which has since been merged. I don't know if the merged branch will cause the same problems or not. Hopefully, but in case not, it may need to get restored to reproduce this bug.

**Comment by denis-yuen** [comment]
Looks like the last release of wdl4s https://github.com/broadinstitute/wdl4s/releases doesn't support flatten https://github.com/openwdl/wdl/search?q=flatten&type=Commits

In other words, #2171 possibly

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

Verified with https://staging.dockstore.org/my-workflows/github.com/DataBiosphere/topmed-workflows/UM_variant_caller_wdl ( https://staging.dockstore.org/my-workflows/github.com/DataBiosphere/topmed-workflows/UM_variant_caller_wdl ) on staging.dockstore.org ( http://staging.dockstore.org ), +1.6.0-beta.3+ ( https://github.com/ga4gh/dockstore/releases/tag/1.6.0-beta.3 ) and +2.3.0-beta.2+ ( https://github.com/dockstore/dockstore-ui2/releases/tag/2.3.0-beta.2 )
