### ISSUE TITLE
Indexing error leading to cwl-runner CLI mismatch

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#2154]
### Expected behaviour

https://dockstore.org/workflows/github.com/cancerit/workflow-seq-import/chksum_seqval_wf_interleaved_fq:0.4.0?tab=info should run via both 
1. Using cwl-runner
2. Using Dockstore CLI

### Actual behaviour

Fails running using cwl-runner as shown by https://gitter.im/ga4gh/dockstore?at=5c77fd05212d0c1e1aae08ca

if_file_name_is_bz2_then_return_null_else_return_in_json_to_output.cwl should be in a toolkit directory as shown in https://github.com/cancerit/workflow-seq-import/tree/0.4.0/cwls/toolkit

However, it seems to index in the pwd as shown by https://dockstore.org/api/api/ga4gh/v2/tools/%2523workflow%252Fgithub.com%252Fcancerit%252Fworkflow-seq-import%252Fchksum_seqval_wf_interleaved_fq/versions/0.4.0/CWL/files

Thanks @byb121 for giving us the heads-up

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-540)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 6 Ferry
┆Issue Number: DOCK-540

**Comment by denis-yuen** [comment]
Another clue. Looks like the zip download gives the correct structure and so does the DB. 
This may be a translation to TRS issue (and then to the GUI) https://gitter.im/ga4gh/dockstore?at=5c78088b2ca5ec5474550aed

**Comment by NatalieEO** [comment]
Hm, not sure if this is working. I was able to reproduce the old bug using production's CLI, but when I try running it with the latest release I get the following.
https://staging.dockstore.org/workflows/github.com/cancerit/workflow-seq-import/chksum_seqval_wf_interleaved_fq:0.4.0?tab=launch 
```duroam-169-233-181-137:~ natalieperez$ cwl-runner https://staging.dockstore.org:443/api/api/ga4gh/v2/tools/%23workflow%2Fgithub.com%2Fcancerit%2Fworkflow-seq-import%2Fchksum_seqval_wf_interleaved_fq/versions/0.4.0/plain-CWL/descriptor/%2Fcwls%2Fchksum_seqval_wf_interleaved_fq.cwl Dockstore.json
/usr/local/bin/cwl-runner 1.0.20180403145700
No handlers could be found for logger "rdflib.term"
/usr/local/lib/python2.7/site-packages/rdflib/plugins/parsers/structureddata.py:30: UserWarning: html5lib not found! RDFa and Microdata parsers will not be available.
  'parsers will not be available.')
Could not load extension schema http://schema.org/docs/schema_org_rdfa.html: html5lib is not installed, cannot use RDFa and Microdata parsers.
https://staging.dockstore.org:443/api/api/ga4gh/v2/tools/%23workflow%2Fgithub.com%2Fcancerit%2Fworkflow-seq-import%2Fchksum_seqval_wf_interleaved_fq/versions/0.4.0/plain-CWL/descriptor/%2Fcwls%2Fchksum_seqval_wf_interleaved_fq.cwl:124:1: unrecognized extension field `dct:creator`.  Did you include a $schemas section?
foreign properties set([])
https://staging.dockstore.org:443/api/api/ga4gh/v2/tools/%23workflow%2Fgithub.com%2Fcancerit%2Fworkflow-seq-import%2Fchksum_seqval_wf_interleaved_fq/versions/0.4.0/plain-CWL/descriptor/%2Fcwls%2Fchksum_seqval_wf_interleaved_fq.cwl:3:1: unrecognized extension field `http://schema.org/codeRepository`.  Did you include a $schemas section?
foreign properties set([])
https://staging.dockstore.org:443/api/api/ga4gh/v2/tools/%23workflow%2Fgithub.com%2Fcancerit%2Fworkflow-seq-import%2Fchksum_seqval_wf_interleaved_fq/versions/0.4.0/plain-CWL/descriptor/%2Fcwls%2Fchksum_seqval_wf_interleaved_fq.cwl:3:1: unrecognized extension field `http://schema.org/license`.  Did you include a $schemas section?
foreign properties set([])
https://staging.dockstore.org:443/api/api/ga4gh/v2/tools/%23workflow%2Fgithub.com%2Fcancerit%2Fworkflow-seq-import%2Fchksum_seqval_wf_interleaved_fq/versions/0.4.0/plain-CWL/descriptor/%2Fcwls%2Fchksum_seqval_wf_interleaved_fq.cwl:3:1: unrecognized extension field `http://schema.org/author`.  Did you include a $schemas section?
foreign properties set([])
https://raw.githubusercontent.com/cancerit/dockstore-cgp-chksum/0.4.1/Dockstore.cwl:15:1: unrecognized extension field `dct:creator`.  Did you include a $schemas section?
foreign properties set([])
https://raw.githubusercontent.com/cancerit/dockstore-cgp-chksum/0.4.1/Dockstore.cwl:15:1: unrecognized extension field `dct:creator`.  Did you include a $schemas section?
foreign properties set([])
[workflow %2Fcwls%2Fchksum_seqval_wf_interleaved_fq.cwl] start
[step if_input_is_bz2_convert_to_gz_else_just_rename] start
Unexpected exception
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/cwltool/workflow.py", line 840, in job
    **kwargs):
  File "/usr/local/lib/python2.7/site-packages/cwltool/command_line_tool.py", line 374, in job
    builder.pathmapper = self.makePathMapper(reffiles, builder.stagedir, **make_path_mapper_kwargs)
  File "/usr/local/lib/python2.7/site-packages/cwltool/command_line_tool.py", line 233, in makePathMapper
    separateDirs=kwargs.get("separateDirs", True))
  File "/usr/local/lib/python2.7/site-packages/cwltool/pathmapper.py", line 229, in __init__
    self.setup(dedup(referenced_files), basedir)
  File "/usr/local/lib/python2.7/site-packages/cwltool/pathmapper.py", line 282, in setup
    self.visit(fob, stagedir, basedir, copy=fob.get("writable"), staged=True)
  File "/usr/local/lib/python2.7/site-packages/cwltool/pathmapper.py", line 271, in visit
    self.visitlisting(obj.get("secondaryFiles", []), stagedir, basedir, copy=copy, staged=staged)
  File "/usr/local/lib/python2.7/site-packages/schema_salad/sourceline.py", line 164, in __exit__
    raise self.makeError(six.text_type(exc_value))
ValidationException: Dockstore.json:2:15: [Errno 2] No such file or directory: '/Users/natalieperez/ftp://ftp.sanger.ac.uk/pub/cancer/dockstore/examples/tiny_interleaved.fq.gz'
[step if_input_is_bz2_convert_to_gz_else_just_rename] Cannot make job: Dockstore.json:2:15: [Errno 2] No such file or directory: '/Users/natalieperez/ftp://ftp.sanger.ac.uk/pub/cancer/dockstore/examples/tiny_interleaved.fq.gz'
[workflow %2Fcwls%2Fchksum_seqval_wf_interleaved_fq.cwl] completed permanentFail
{
    "chksum_json": null, 
    "results_manifest": null, 
    "interleaved_fastq_out": null, 
    "chksum_put_server_response": null
}
Final process status is permanentFail
```

**Comment by denis-yuen** [comment]
@NatalieEO 
What does your `Dockstore.json` look like? 
`/Users/natalieperez/ftp://ftp.sanger.ac.uk/pub/cancer/dockstore/examples/tiny_interleaved.fq.gz` seems odd and unlikely to be affected by a server-side bug. 

We might have a new client bug on our hands

**Comment by NatalieEO** [comment]
```eduroam-169-233-181-137:~ natalieperez$ cat Dockstore.json
{
  "fastq_in": {
    "path": "ftp://ftp.sanger.ac.uk/pub/cancer/dockstore/examples/tiny_interleaved.fq.gz",
    "class": "File"
  },
  "put_address":"https://postman-echo.com/put",
  "chksum_json": {
    "path":"/tmp/chksum_fq_inter_result.json",
    "class": "File"
  },
  "chksum_put_server_response": {
    "path":"/tmp/server_response_1.json",
    "class": "File"
  },
  "interleaved_fastq_out": {
    "path":"/tmp/interleaved.fq.gz",
    "class": "File"
  },
  "results_manifest": {
    "path":"/tmp/rg_file_manifest.txt",
    "class": "File"
  }
}```

**Comment by denis-yuen** [comment]
Oh, I see now. 
So dockstore cli supports ftp, cwltool/cwl-runner does not support ftp, not yet anyway. 

So when testing with cwl-runner, you'll need to have the files available locally (and modify the Dockstore.json accordingly).

**Comment by NatalieEO** [comment]
@denis-yuen thanks for the help. cwl-runner is working using DockstoreAPI - 1.6.0-beta.3. Was able to successfully launch https://staging.dockstore.org/workflows/github.com/cancerit/workflow-seq-import/chksum_seqval_wf_interleaved_fq:0.4.0?tab=launch using Dockstore CLI and cwl-runner.
