### ISSUE TITLE
Migration fails on deploy to staging

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#2168]
### Expected behaviour

Migration works

### Actual behaviour

```
migration_1        | INFO  [2019-03-01 21:53:59,539] liquibase.executor.jvm.JdbcExecutor: ALTER TABLE public.organization ADD displayname VARCHAR(50) NOT NULL
migration_1        | ERROR [2019-03-01 21:53:59,553] liquibase.changelog.ChangeSet: Change Set migrations.1.6.0.xml::addDisplayNameToOrganization::aduncan failed.  Error: ERROR: column "displayname" contains null values [Failed SQL: ALTER TABLE public.organization ADD displayname VARCHAR(50) NOT NULL]
migration_1        | INFO  [2019-03-01 21:53:59,556] liquibase.lockservice.StandardLockService: Successfully released change log lock
migration_1        | liquibase.exception.MigrationFailedException: Migration failed for change set migrations.1.6.0.xml::addDisplayNameToOrganization::aduncan:
migration_1        |      Reason: liquibase.exception.DatabaseException: ERROR: column "displayname" contains null values [Failed SQL: ALTER TABLE public.organization ADD displayname VARCHAR(50) NOT NULL]
migration_1        |    at liquibase.changelog.ChangeSet.execute(ChangeSet.java:637)
migration_1        |    at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:53)
migration_1        |    at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:78)
migration_1        |    at liquibase.Liquibase.update(Liquibase.java:202)
migration_1        |    at liquibase.Liquibase.update(Liquibase.java:179)
migration_1        |    at liquibase.Liquibase.update(Liquibase.java:175)
migration_1        |    at liquibase.Liquibase.update(Liquibase.java:168)
migration_1        |    at io.dropwizard.migrations.DbMigrateCommand.run(DbMigrateCommand.java:68)
migration_1        |    at io.dropwizard.migrations.DbCommand.run(DbCommand.java:55)
migration_1        |    at io.dropwizard.migrations.AbstractLiquibaseCommand.run(AbstractLiquibaseCommand.java:68)
migration_1        |    at io.dropwizard.cli.ConfiguredCommand.run(ConfiguredCommand.java:87)
migration_1        |    at io.dropwizard.cli.Cli.run(Cli.java:78)
migration_1        |    at io.dropwizard.Application.run(Application.java:93)
migration_1        |    at io.dockstore.webservice.DockstoreWebserviceApplication.main(DockstoreWebserviceApplication.java:141)
migration_1        | Caused by: liquibase.exception.DatabaseException: ERROR: column "displayname" contains null values [Failed SQL: ALTER TABLE public.organization ADD displayname VARCHAR(50) NOT NULL]
migration_1        |    at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:356)
migration_1        |    at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:57)
migration_1        |    at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:125)
migration_1        |    at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1229)
migration_1        |    at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1211)
migration_1        |    at liquibase.changelog.ChangeSet.execute(ChangeSet.java:600)
migration_1        |    ... 13 more
migration_1        | Caused by: org.postgresql.util.PSQLException: ERROR: column "displayname" contains null values
migration_1        |    at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2477)
migration_1        |    at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2190)
migration_1        |    at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:300)
migration_1        |    at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:428)
migration_1        |    at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:354)
migration_1        |    at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:301)
migration_1        |    at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:287)
migration_1        |    at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:264)
migration_1        |    at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:260)
migration_1        |    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
migration_1        |    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
migration_1        |    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
migration_1        |    at java.lang.reflect.Method.invoke(Method.java:498)
migration_1        |    at org.apache.tomcat.jdbc.pool.StatementFacade$StatementProxy.invoke(StatementFacade.java:114)
migration_1        |    at com.sun.proxy.$Proxy32.execute(Unknown Source)
migration_1        |    at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:352)
migration_1        |    ... 18 more
migration_1        | 2019/03/01 21:53:59 Command finished successfully.
composesetup_migration_1 exited with code 0

```

**Comment by denis-yuen** [comment]
Nevermind, loading a fresh production dump, it just looks like migration is not compatible with older 1.6.0 databases
