### ISSUE TITLE
UpgradeTestIT not compatible with new releases?

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#235]
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running io.dockstore.client.cli.UpgradeTestIT
[INFO] 16:19:03.587 [main] DEBUG o.a.c.c.ConfigurationUtils - ConfigurationUtils.locate(): base is null, name is /tmp/1463429943555-0/config2322661662724646072config
[INFO] 16:19:03.589 [main] DEBUG o.a.c.c.DefaultFileSystem - Could not locate file /tmp/1463429943555-0/config2322661662724646072config at null: no protocol: /tmp/1463429943555-0/config2322661662724646072config
[INFO] 16:19:03.590 [main] DEBUG o.a.c.c.ConfigurationUtils - Loading configuration from the absolute path /tmp/1463429943555-0/config2322661662724646072config
[INFO] Current Dockstore version: 0.4-beta.1
[INFO] java.lang.NullPointerException
[INFO] 	at io.dockstore.client.cli.Client.openCurrentVersion(Client.java:191)
[INFO] 	at io.dockstore.client.cli.Client.compareVersion(Client.java:225)
[INFO] 	at io.dockstore.client.cli.Client.upgrade(Client.java:383)
[INFO] 	at io.dockstore.client.cli.Client.run(Client.java:687)
[INFO] 	at io.dockstore.client.cli.Client.main(Client.java:716)
[INFO] 	at io.dockstore.client.cli.UpgradeTestIT.upgradeTest(Upgr
```

It looks like the test relies upon a specific local version too.

**Comment by denis-yuen** [comment]
One additional note, we should squash the message when working on a development version locally
e.g.
```
cannot find id in https://api.github.com/repos/ga4gh/dockstore/releases/tags/0.4-beta.2-SNAPSHOT
java.io.FileNotFoundException: https://api.github.com/repos/ga4gh/dockstore/releases/tags/0.4-beta.2-SNAPSHOT
```
