### ISSUE TITLE
Workflow name not allowed to be blank as described in "Register Workflow" dialog

### ISSUE THREAD

**Issue by jpatricia** [ga4gh/dockstore#253]
1. See whether blank named workflows work as expected
2. Fix dialog box and/or error message

Lead on the webservice side:

```
10.0.29.14 - - [31/May/2016:19:10:28 +0000] "GET /workflows/9/wdl?tag=master HTTP/1.1" 200 231 "http://10.0.29.14:9001/my-workflows" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.63 Safari/537.36" 5
ERROR [2016-05-31 19:11:47,567] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: 1672f7bf739cf3d6
! java.lang.NullPointerException: null
! at io.dockstore.webservice.resources.WorkflowResource.manualRegister(WorkflowResource.java:574) ~[classes/:na]
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91]
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_91]
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91]
! at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_91]
! at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[jersey-server-2.22.1.jar:na]
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[jersey-server-2.22.1.jar:na]
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[jersey-server-2.22.1.jar:na]
```

**Comment by denis-yuen** [comment]
This seems to work now
