### ISSUE TITLE
Dockstore launcher needs to support secondary files

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#364]
### Expected behaviour

`dockstore tool launch --entry Dockstore.cwl --local-entry --json test.json` should work

### Actual behaviour

Dies with an exception, looks like we do not process secondary files properly for provisioning

```
$ dockstore tool launch --entry Dockstore.cwl --local-entry --json test.json 
Creating directories for run of Dockstore launcher at: ./datastore//launcher-ca3b0bbf-daa4-4749-b36a-361fe6dd7582
Provisioning your input files to your local machine
Downloading: #input from test.fastq into directory: /home/dyuen/dockstore-tool-bwa-aln/./datastore/launcher-ca3b0bbf-daa4-4749-b36a-361fe6dd7582/inputs/f03052ba-8540-4ef1-86cb-770fae721078
Downloading: #prefix from hg19.fa into directory: /home/dyuen/dockstore-tool-bwa-aln/./datastore/launcher-ca3b0bbf-daa4-4749-b36a-361fe6dd7582/inputs/93e47897-313f-4ede-a7ec-b2159a98465b
Calling out to cwltool to run your tool
Executing: cwltool --enable-dev --non-strict --enable-net --outdir /home/dyuen/dockstore-tool-bwa-aln/./datastore/launcher-ca3b0bbf-daa4-4749-b36a-361fe6dd7582/outputs/ --tmpdir-prefix /home/dyuen/dockstore-tool-bwa-aln/./datastore/launcher-ca3b0bbf-daa4-4749-b36a-361fe6dd7582/working/ /home/dyuen/dockstore-tool-bwa-aln/Dockstore.cwl /home/dyuen/dockstore-tool-bwa-aln/./datastore/launcher-ca3b0bbf-daa4-4749-b36a-361fe6dd7582/workflow_params.json
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.access$200(DefaultExecutor.java:48)
	at org.apache.commons.exec.DefaultExecutor$1.run(DefaultExecutor.java:200)
	at java.lang.Thread.run(Thread.java:745)
java.lang.RuntimeException: problems running command: cwltool --enable-dev --non-strict --enable-net --outdir /home/dyuen/dockstore-tool-bwa-aln/./datastore/launcher-ca3b0bbf-daa4-4749-b36a-361fe6dd7582/outputs/ --tmpdir-prefix /home/dyuen/dockstore-tool-bwa-aln/./datastore/launcher-ca3b0bbf-daa4-4749-b36a-361fe6dd7582/working/ /home/dyuen/dockstore-tool-bwa-aln/Dockstore.cwl /home/dyuen/dockstore-tool-bwa-aln/./datastore/launcher-ca3b0bbf-daa4-4749-b36a-361fe6dd7582/workflow_params.json
$  cwltool --enable-dev --non-strict --enable-net --outdir /home/dyuen/dockstore-tool-bwa-aln/./datastore/launcher-ca3b0bbf-daa4-4749-b36a-361fe6dd7582/outputs/ --tmpdir-prefix /home/dyuen/dockstore-tool-bwa-aln/./datastore/launcher-ca3b0bbf-daa4-4749-b36a-361fe6dd7582/working/ /home/dyuen/dockstore-tool-bwa-aln/Dockstore.cwl /home/dyuen/dockstore-tool-bwa-aln/./datastore/launcher-ca3b0bbf-daa4-4749-b36a-361fe6dd7582/workflow_params.json
/usr/local/bin/cwltool 1.0.20160805221855
Workflow error, try again with --debug for more information:
  Missing input file [Errno 2] No such file or directory: '/home/dyuen/dockstore-tool-bwa-aln/./datastore/launcher-ca3b0bbf-daa4-4749-b36a-361fe6dd7582/inputs/93e47897-313f-4ede-a7ec-b2159a98465b/prefix.bwt'
dyuen@orz:~/dockstore-tool-bwa-aln$ 

```

### Steps to reproduce the behaviour 

Test with https://github.com/CancerCollaboratory/dockstore-tool-bwa-aln CWL 1.0 version

**Comment by denis-yuen** [comment]
Verified functional on staging with local files (test.json in repo) and with remote 
```
{
    "input": {
        "class": "File",
        "path": "test.fastq"
    },
    "prefix": {
        "class": "File",
        "path": "https://github.com/CancerCollaboratory/dockstore-tool-bwa-aln/raw/master/hg19.fa"
    },
    "output": {
        "class": "File",
        "path": "test.sai"
    },
    "output_name": "test.sai"
}
```
