### ISSUE TITLE
Reports wrong content-type for "plain-CWL" type, missing character encoding

### ISSUE THREAD

**Issue by tetron** [ga4gh/dockstore#378]
https://staging.dockstore.org:8443/api/ga4gh/v1/tools/quay.io%2Fcollaboratory%2Fdockstore-tool-bwa-samse/versions/master/plain-CWL/descriptor

```
HTTP/1.1 200 OK
Date: Tue, 16 Aug 2016 22:27:06 GMT
Content-Type: application/json
Vary: Accept-Encoding
Content-Length: 1810
```

The content type should probably be text/plain.  Application/json is definitely wrong. Unfortunately, there doesn't appear to be standard mime type for YAML, there are a few different conventions in use (https://stackoverflow.com/questions/332129/yaml-mime-type).

Per the CWL spec, CWL files should be encoded UTF-8.  The headers should explicitly supply this as the character encoding.

This is a blocker issue, using the Python requests library to fetch the above link gets decoded using the wrong character set, which has the effect of causing the YAML parser to fail.

**Comment by denis-yuen** [comment]
@tetron 

Hi, 
Splitting this out into two issues
### Content-type

Took a look at this, the intent was that, the web-service just gives what you ask for, with the accept header overriding the query parameter if present. 

Text/plain is returned as the content-type for a YAML CWL document.

For example
```
$ wget --header='Accept: text/plain' https://staging.dockstore.org:8443/api/ga4gh/v1/tools/quay.io%2Fcollaboratory%2Fdockstore-tool-bwa-samse/versions/master/CWL/descriptor && file -i descriptor && head -n 5 descriptor && rm descriptor
--2016-08-17 10:41:23--  https://staging.dockstore.org:8443/api/ga4gh/v1/tools/quay.io%2Fcollaboratory%2Fdockstore-tool-bwa-samse/versions/master/CWL/descriptor
Resolving staging.dockstore.org (staging.dockstore.org)... 52.3.124.195
Connecting to staging.dockstore.org (staging.dockstore.org)|52.3.124.195|:8443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1810 (1.8K) [text/plain]
Saving to: ‘descriptor’

100%[=====================================================================================>] 1,810       --.-K/s   in 0s      

2016-08-17 10:41:23 (703 MB/s) - ‘descriptor’ saved [1810/1810]

descriptor: text/x-c++; charset=utf-8
#!/usr/bin/env cwl-runner

class: CommandLineTool

description: |
``` 
and 
```
$ wget --header='Accept: application/json' https://staging.dockstore.org:8443/api/ga4gh/v1/tools/quay.io%2Fcollaboratory%2Fdockstore-tool-bwa-samse/versions/master/CWL/descriptor && file -i descriptor && head -n 5 descriptor && rm descriptor
--2016-08-17 10:41:44--  https://staging.dockstore.org:8443/api/ga4gh/v1/tools/quay.io%2Fcollaboratory%2Fdockstore-tool-bwa-samse/versions/master/CWL/descriptor
Resolving staging.dockstore.org (staging.dockstore.org)... 52.3.124.195
Connecting to staging.dockstore.org (staging.dockstore.org)|52.3.124.195|:8443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2092 (2.0K) [application/json]
Saving to: ‘descriptor’

100%[=====================================================================================>] 2,092       --.-K/s   in 0s      

2016-08-17 10:41:44 (153 MB/s) - ‘descriptor’ saved [2092/2092]

descriptor: text/plain; charset=utf-8
{"type":"CWL","descriptor":"#!/usr/bin/env cwl-runner\n\nclass: CommandLineTool\n\ndescription: |\n  Usage: bwa samse [-n max_occ] [-f out.sam] [-r RG_line] <prefix> <in.sai> <in.fq>\n\ndct:contributor:\n  \"@id\": \"http://orcid.org/orcid.org/0000-0002
```

Doing a bit of testing, I get this:

| accept-header | query parameter | returns |
|---------------|-----------------|---------|
| (missing)     | plain-CWL       | yaml    |
| (missing)     | CWL             | json    |
| plain/text    | plain-CWL       | yaml    |
| plain/text    | CWL             | yaml    |
| json          | plain-CWL       | yaml    |
| json          | CWL             | json    |

As you can see, there's a bug in row 5, where you get yaml instead of the expected json. However, that does not seem to explain your observation. What accept-header are you sending?

### Encoding

My understanding is that Jersey always returns UTF-8 by default, which seems to be verified by the `file -i` tests above.  Is it possible that the Requests library is assuming some other character set?

**Comment by tetron** [comment]
```
>>> import requests
>>> requests.get("https://staging.dockstore.org:8443/api/ga4gh/v1/tools/quay.io%2Fcollaboratory%2Fdockstore-tool-bwa-samse/versions/master/plain-CWL/descriptor")
<Response [200]>
>>> resp = requests.get("https://staging.dockstore.org:8443/api/ga4gh/v1/tools/quay.io%2Fcollaboratory%2Fdockstore-tool-bwa-samse/versions/master/plain-CWL/descriptor")
>>> resp
<Response [200]>
>>> resp.text
u'#!/usr/bin/env cwl-runner\n\nclass: CommandLineTool\n\ndescription: |\n  Usage: bwa samse [-n max_occ] [-f out.sam] [-r RG_line] <prefix> <in.sai> <in.fq>\n\ndct:contributor:\n  "@id": "http://orcid.org/orcid.org/0000-0002-6130-1021"\n  foaf:name: Denis Yuen\n  foaf:mbox: "mailto:help@cancercollaboratory.org"\n\ndct:creator:\n  "@id": "http://orcid.org/0000-0001-9102-5681"\n  foaf:name: "Andrey Kartashov"\n  foaf:mbox: "mailto:Andrey.Kartashov@cchmc.org"\n\ndct:description: "Developed at Cincinnati Children\xe2\x80\x99s Hospital Medical Center for the CWL consortium http://commonwl.org/ Original URL: https://github.com/common-workflow-language/workflows"\n\ncwlVersion: draft-3\n\n\nrequirements:\n  - class: DockerRequirement\n    dockerPull: quay.io/collaboratory/dockstore-tool-bwa-samse\n\n\ninputs:\n  - id: "#prefix"\n    type: File\n    inputBinding:\n      position: 4\n    secondaryFiles:\n      - ".amb"\n      - ".ann"\n      - ".pac"\n      - ".rpac"\n      - ".bwt"\n      - ".rbwt"\n      - ".sa"\n      - ".rsa"\n\n  - id: "#insai"\n    type: File\n    inputBinding:\n      position: 5\n\n  - id: "#infq"\n    type: File\n    inputBinding:\n      position: 6\n\n  - id: "#outsam"\n    type: string\n    inputBinding:\n      position: 1\n      prefix: "-f"\n\n  - id: "#max_occ"\n    type: ["null", int ]\n    description: |\n      Maximum number of alignments to output in the XA tag for reads paired properly. If a read has more than INT hits, the XA tag will not be written. [3]\n    inputBinding:\n      position: 1\n      prefix: "-n"\n\n  - id: "#RG_line"\n    type: ["null", string ]\n    description: |\n      Specify the read group in a format like `@RG\\tID:foo\\tSM:bar\'. [null]\n    inputBinding:\n      position: 1\n      prefix: "-r"\n\noutputs:\n  - id: "#aligned"\n    type: File\n    outputBinding:\n      glob: $(inputs.outsam)\n\nbaseCommand: ["bwa","samse"]\n\n'
>>> import yaml
>>> yaml.load(resp.text)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/peter/work/cwl-venv/local/lib/python2.7/site-packages/PyYAML-3.11-py2.7-linux-x86_64.egg/yaml/__init__.py", line 69, in load
  File "/home/peter/work/cwl-venv/local/lib/python2.7/site-packages/PyYAML-3.11-py2.7-linux-x86_64.egg/yaml/loader.py", line 34, in __init__
  File "/home/peter/work/cwl-venv/local/lib/python2.7/site-packages/PyYAML-3.11-py2.7-linux-x86_64.egg/yaml/reader.py", line 74, in __init__
  File "/home/peter/work/cwl-venv/local/lib/python2.7/site-packages/PyYAML-3.11-py2.7-linux-x86_64.egg/yaml/reader.py", line 144, in check_printable
yaml.reader.ReaderError: unacceptable character #x0080: special characters are not allowed
  in "<unicode string>", position 
>>> resp.headers
{'date': 'Wed, 17 Aug 2016 16:14:22 GMT', 'vary': 'Accept-Encoding', 'content-length': '837', 'content-type': 'application/json', 'content-encoding': 'gzip'}
>>> resp.request.headers
{'Connection': 'keep-alive', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'User-Agent': 'python-requests/2.7.0 CPython/2.7.9 Linux/4.6.2'}
```

**Comment by tetron** [comment]
```
$ curl -v https://staging.dockstore.org:8443/api/ga4gh/v1/tools/quay.io%252Fcollaboratory%252Fdockstore-tool-bwa-aln/versions/master/plain-CWL/descriptor
> GET /api/ga4gh/v1/tools/quay.io%252Fcollaboratory%252Fdockstore-tool-bwa-aln/versions/master/plain-CWL/descriptor HTTP/1.1
> User-Agent: curl/7.38.0
> Host: staging.dockstore.org:8443
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Wed, 17 Aug 2016 16:18:28 GMT
< Content-Type: application/json
< Vary: Accept-Encoding
< Content-Length: 2844
```

**Comment by tetron** [comment]
So, when the client provides `Accept: */*` (which is the default for both requests and curl and probably many other http client libraries), dockstore returns `application/json` as the content-type for `plain-CWL` (which seems wrong) and no character set.  I am proposing that the content-type returned for `Accept: */*` and `plain-CWL` should be:

```
Content-Type: text/plain; charset=utf-8
```

**Comment by denis-yuen** [comment]
As discussed on gitter, we're going to simplify for this endpoint and use only the query parameter, ignoring the accept header.

We're also going to add charset utf-8 explicitly in the content-type response to see if the requests library handles it better.

**Comment by denis-yuen** [comment]
Verified behaviour on staging
* utf-8 reported explicitly
* output format is based only on query parameter
* python requests seems compatible (tested with https://github.com/ga4gh/dockstore/issues/378#issuecomment-240463291 )
