### ISSUE TITLE
dockstore convert doesn't recognize class synData

### ISSUE THREAD

**Issue by Jeltje** [ga4gh/dockstore#525]
### Expected behaviour
Create json output for [this workflow](https://raw.githubusercontent.com/Sage-Bionetworks/SMC-RNA-Examples/master/workflow/smcFusionQuant-INTEGRATE-workflow.cwl)
### Actual behaviour
```
dockstore workflow convert cwl2json --cwl smcFusionQuant-INTEGRATE-workflow.cwl > Integrate.json
java.lang.ClassNotFoundException: io.cwl.avro.file:///mnt/dockstore/integrate/SMC-RNA-Examples/workflow/synData
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at io.cwl.avro.CWL.getCWLObject(CWL.java:177)
        at io.cwl.avro.CWL.lambda$getTypeSafeCWLToolDocument$2(CWL.java:158)
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
        at com.google.gson.Gson.fromJson(Gson.java:887)
        at com.google.gson.Gson.fromJson(Gson.java:852)
        at com.google.gson.Gson.fromJson(Gson.java:801)
        at com.google.gson.Gson.fromJson(Gson.java:773)
        at io.cwl.avro.CWL.extractRunJson(CWL.java:48)
        at io.dockstore.client.cli.nested.AbstractEntryClient.cwl2json(AbstractEntryClient.java:494)
        at io.dockstore.client.cli.nested.AbstractEntryClient.convert(AbstractEntryClient.java:467)
        at io.dockstore.client.cli.nested.AbstractEntryClient.processEntryCommands(AbstractEntryClient.java:215)
        at io.dockstore.client.cli.Client.run(Client.java:698)
        at io.dockstore.client.cli.Client.main(Client.java:759)
java.lang.NullPointerException
```

### Steps to reproduce the behaviour 

`dockstore workflow convert cwl2json --cwl smcFusionQuant-INTEGRATE-workflow.cwl > Integrate.json`

### Environment (Browser or OS and Dockstore version)
`Ubuntu 15.04`
`pip list`
```
avro (1.8.1)
cwl-runner (1.0)
cwltool (1.0.20160712154127)
html5lib (0.999999999)
isodate (0.5.4)
keepalive (0.5)
mistune (0.7.3)
pip (9.0.1)
pyparsing (2.1.10)
rdflib (4.2.1)
rdflib-jsonld (0.4.0)
requests (2.11.1)
ruamel.ordereddict (0.4.9)
ruamel.yaml (0.11.11)
schema-salad (1.14.20160708181155)
setuptools (28.8.0)
shellescape (3.4.1)
six (1.10.0)
SPARQLWrapper (1.7.6)
typing (3.5.2.2)
webencodings (0.5)
```

**Comment by denis-yuen** [comment]
Could you give this a try with dockstore 1.1? 
This looks fixed already on our side.

**Comment by Jeltje** [comment]
Good catch! However...

`dockstore --upgrade`
```
Current Dockstore version: 1.0.1
Upgrading to most recent stable release (1.0.1 -> 1.1)
Download complete. You are now on version 1.1 of Dockstore.
```
`dockstore --version`
```
Downloading Dockstore to /home/ubuntu/.dockstore/self-installs/dockstore-client-1.1.jar now...
https://seqwaremaven.oicr.on.ca/artifactory/collab-release/io/dockstore/dockstore-client/1.1/dockstore-client-1.1.jar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 63.3M  100 63.3M    0     0   429k      0  0:02:30  0:02:30 --:--:--  494k
Exception in thread "main" java.lang.NoClassDefFoundError: javax/annotation/Priority
        at org.glassfish.jersey.model.internal.CommonConfig$2.compare(CommonConfig.java:597)
        at org.glassfish.jersey.model.internal.CommonConfig$2.compare(CommonConfig.java:594)
        at java.util.TreeMap.compare(java.base@9-internal/TreeMap.java:1292)
        at java.util.TreeMap.put(java.base@9-internal/TreeMap.java:536)
        at java.util.TreeSet.add(java.base@9-internal/TreeSet.java:255)
        at java.util.AbstractCollection.addAll(java.base@9-internal/AbstractCollection.java:352)
        at java.util.TreeSet.addAll(java.base@9-internal/TreeSet.java:312)
        at org.glassfish.jersey.model.internal.CommonConfig.configureAutoDiscoverableProviders(CommonConfig.java:616)
        at org.glassfish.jersey.client.ClientConfig$State.configureAutoDiscoverableProviders(ClientConfig.java:364)
        at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:399)
        at org.glassfish.jersey.client.ClientConfig$State.access$000(ClientConfig.java:90)
        at org.glassfish.jersey.client.ClientConfig$State$3.get(ClientConfig.java:122)
        at org.glassfish.jersey.client.ClientConfig$State$3.get(ClientConfig.java:119)
        at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:340)
        at org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:733)
        at org.glassfish.jersey.client.ClientRequest.getConfiguration(ClientRequest.java:286)
        at org.glassfish.jersey.client.JerseyInvocation.validateHttpMethodAndEntity(JerseyInvocation.java:135)
        at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:105)
        at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:101)
        at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:92)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:411)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:311)
        at io.swagger.client.ApiClient.invokeAPI(ApiClient.java:485)
        at io.swagger.client.api.UsersApi.getUser(UsersApi.java:337)
        at io.dockstore.client.cli.Client.setupClientEnvironment(Client.java:783)
        at io.dockstore.client.cli.Client.run(Client.java:676)
        at io.dockstore.client.cli.Client.main(Client.java:796)
Caused by: java.lang.ClassNotFoundException: javax.annotation.Priority
        at jdk.internal.loader.BuiltinClassLoader.loadClass(java.base@9-internal/BuiltinClassLoader.java:366)
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(java.base@9-internal/ClassLoaders.java:184)
        at java.lang.ClassLoader.loadClass(java.base@9-internal/ClassLoader.java:419)
        ... 27 more
```
And now my dockstore is broken...

**Comment by Jeltje** [comment]
I tried to do it from scratch
```
wget https://github.com/ga4gh/dockstore/releases/download/1.1/dockstore
chmod 775 dockstore
mv dockstore ~/bin
dockstore
```
but got the same results

Let me know if I should file a separate bug report for this.

**Comment by denis-yuen** [comment]
Hmmm, try deleting ~/.dockstore/self-installs
That is where the script caches your Dockstore jar
If it persists, do open a separate bug report, thanks!

**Comment by denis-yuen** [comment]
Second issue continued in #528
