### ISSUE TITLE
Dockstore is not compatible with OpenJDK 9

### ISSUE THREAD

**Issue by Jeltje** [ga4gh/dockstore#528]
### Expected behaviour
Installing dockstore 1.1

### Actual behaviour
```
Downloading Dockstore to /home/ubuntu/.dockstore/self-installs/dockstore-client-1.1.jar now...
https://seqwaremaven.oicr.on.ca/artifactory/collab-release/io/dockstore/dockstore-client/1.1/dockstore-client-1.1.jar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 63.3M  100 63.3M    0     0   346k      0  0:03:07  0:03:07 --:--:--  369k
Exception in thread "main" java.lang.NoClassDefFoundError: javax/annotation/Priority
        at org.glassfish.jersey.model.internal.CommonConfig$2.compare(CommonConfig.java:597)
        at org.glassfish.jersey.model.internal.CommonConfig$2.compare(CommonConfig.java:594)
        at java.util.TreeMap.compare(java.base@9-internal/TreeMap.java:1292)
        at java.util.TreeMap.put(java.base@9-internal/TreeMap.java:536)
        at java.util.TreeSet.add(java.base@9-internal/TreeSet.java:255)
        at java.util.AbstractCollection.addAll(java.base@9-internal/AbstractCollection.java:352)
        at java.util.TreeSet.addAll(java.base@9-internal/TreeSet.java:312)
        at org.glassfish.jersey.model.internal.CommonConfig.configureAutoDiscoverableProviders(CommonConfig.java:616)
        at org.glassfish.jersey.client.ClientConfig$State.configureAutoDiscoverableProviders(ClientConfig.java:364)
        at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:399)
        at org.glassfish.jersey.client.ClientConfig$State.access$000(ClientConfig.java:90)
        at org.glassfish.jersey.client.ClientConfig$State$3.get(ClientConfig.java:122)
        at org.glassfish.jersey.client.ClientConfig$State$3.get(ClientConfig.java:119)
        at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:340)
        at org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:733)
        at org.glassfish.jersey.client.ClientRequest.getConfiguration(ClientRequest.java:286)
        at org.glassfish.jersey.client.JerseyInvocation.validateHttpMethodAndEntity(JerseyInvocation.java:135)
        at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:105)
        at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:101)
        at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:92)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:411)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:311)
        at io.swagger.client.ApiClient.invokeAPI(ApiClient.java:485)
        at io.swagger.client.api.UsersApi.getUser(UsersApi.java:337)
        at io.dockstore.client.cli.Client.setupClientEnvironment(Client.java:783)
        at io.dockstore.client.cli.Client.run(Client.java:676)
        at io.dockstore.client.cli.Client.main(Client.java:796)
Caused by: java.lang.ClassNotFoundException: javax.annotation.Priority
        at jdk.internal.loader.BuiltinClassLoader.loadClass(java.base@9-internal/BuiltinClassLoader.java:366)
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(java.base@9-internal/ClassLoaders.java:184)
        at java.lang.ClassLoader.loadClass(java.base@9-internal/ClassLoader.java:419)
        ... 27 more

```

### Steps to reproduce the behaviour 
```
rm -rf ~/.dockstore/self-installs
wget https://github.com/ga4gh/dockstore/releases/download/1.1/dockstore
chmod 775 dockstore
./dockstore
```

### Environment (Browser or OS and Dockstore version)
`Ubuntu 16.04`

**Comment by denis-yuen** [comment]
@Jeltje 

Hi,
I think I've managed to replicate this error message, but it doesn't seem to be a Dockstore 1.1 issue.
It looks like we're (either Dockstore 1.0 or 1.1) not compatible with Java 9 OpenJDK. It is possible that your runtime environment has been updated recently? 

(It looks like a simple command succeeds on Oracle JDK 9, we normally test with Oracle JDK 8)


```
$ java -version
java version "9-ea"
Java(TM) SE Runtime Environment (build 9-ea+140)
Java HotSpot(TM) 64-Bit Server VM (build 9-ea+140, mixed mode)
$ dockstore --version
Dockstore version 1.1
You are running the latest stable version...
If you wish to upgrade to the latest unstable version, please use the following command:
   dockstore --upgrade-unstable
```

```
$ java -version
openjdk version "9-internal"
OpenJDK Runtime Environment (build 9-internal+0-2016-04-14-195246.buildd.src)
OpenJDK 64-Bit Server VM (build 9-internal+0-2016-04-14-195246.buildd.src, mixed mode)
$ dockstore --server-metadata
Exception in thread "main" java.lang.NoClassDefFoundError: javax/annotation/Priority
	at org.glassfish.jersey.model.internal.CommonConfig$2.compare(CommonConfig.java:597)
	at org.glassfish.jersey.model.internal.CommonConfig$2.compare(CommonConfig.java:594)
	at java.util.TreeMap.compare(java.base@9-internal/TreeMap.java:1292)
	at java.util.TreeMap.put(java.base@9-internal/TreeMap.java:536)
	at java.util.TreeSet.add(java.base@9-internal/TreeSet.java:255)
	at java.util.AbstractCollection.addAll(java.base@9-internal/AbstractCollection.java:352)
	at java.util.TreeSet.addAll(java.base@9-internal/TreeSet.java:312)
	at org.glassfish.jersey.model.internal.CommonConfig.configureAutoDiscoverableProviders(CommonConfig.java:616)
	at org.glassfish.jersey.client.ClientConfig$State.configureAutoDiscoverableProviders(ClientConfig.java:364)
	at org.glassfish.jersey.client.ClientConfig$State.initRuntime(ClientConfig.java:399)
	at org.glassfish.jersey.client.ClientConfig$State.access$000(ClientConfig.java:90)
	at org.glassfish.jersey.client.ClientConfig$State$3.get(ClientConfig.java:122)
	at org.glassfish.jersey.client.ClientConfig$State$3.get(ClientConfig.java:119)
	at org.glassfish.jersey.internal.util.collection.Values$LazyValueImpl.get(Values.java:340)
	at org.glassfish.jersey.client.ClientConfig.getRuntime(ClientConfig.java:733)
	at org.glassfish.jersey.client.ClientRequest.getConfiguration(ClientRequest.java:286)
	at org.glassfish.jersey.client.JerseyInvocation.validateHttpMethodAndEntity(JerseyInvocation.java:135)
	at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:105)
	at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:101)
	at org.glassfish.jersey.client.JerseyInvocation.<init>(JerseyInvocation.java:92)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:411)
	at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:311)
	at io.swagger.client.ApiClient.invokeAPI(ApiClient.java:485)
	at io.swagger.client.api.UsersApi.getUser(UsersApi.java:337)
	at io.dockstore.client.cli.Client.setupClientEnvironment(Client.java:783)
	at io.dockstore.client.cli.Client.run(Client.java:676)
	at io.dockstore.client.cli.Client.main(Client.java:796)
Caused by: java.lang.ClassNotFoundException: javax.annotation.Priority
	at jdk.internal.loader.BuiltinClassLoader.loadClass(java.base@9-internal/BuiltinClassLoader.java:366)
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(java.base@9-internal/ClassLoaders.java:184)
	at java.lang.ClassLoader.loadClass(java.base@9-internal/ClassLoader.java:419)
	... 27 more

```

**Comment by Jeltje** [comment]
That's quite likely the problem. I will downgrade and report back.

**Comment by Jeltje** [comment]
That worked, thanks
