### ISSUE TITLE
Pass through output when cwltool dies

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#533]
### Desired behaviour

Currently, it looks like we do not properly pass through output when cwltool dies when we call out to it for pre-processing. We should do that in order to make debugging easier. 

```
ubuntu@docker-runner:~/cgpmap$ dockstore tool convert cwl2json --debug --cwl Dockstore.cwl 
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
at org.apache.commons.exec.DefaultExecutor.access$200(DefaultExecutor.java:48)
at org.apache.commons.exec.DefaultExecutor$1.run(DefaultExecutor.java:200)
at java.lang.Thread.run(Thread.java:745)
java.lang.RuntimeException: problems running command: cwltool --non-strict --print-pre Dockstore.cwl
at io.cwl.avro.Utilities.executeCommand(Utilities.java:91)
at io.cwl.avro.CWL.parseCWL(CWL.java:285)
at io.dockstore.client.cli.nested.AbstractEntryClient.cwl2json(AbstractEntryClient.java:543)
at io.dockstore.client.cli.nested.AbstractEntryClient.convert(AbstractEntryClient.java:512)
at io.dockstore.client.cli.nested.AbstractEntryClient.processEntryCommands(AbstractEntryClient.java:244)
at io.dockstore.client.cli.Client.run(Client.java:704)
at io.dockstore.client.cli.Client.main(Client.java:796)
Caused by: org.apache.commons.exec.ExecuteException: problems running command: cwltool --non-strict --print-pre Dockstore.cwl (Exit value: 1)
at io.cwl.avro.Utilities.executeCommand(Utilities.java:87)
... 6 more

ubuntu@docker-runner:~/cgpmap$ cwltool --non-strict --print-pre Dockstore.cwl
/usr/local/bin/cwltool 1.0.20161114152756
Resolved 'Dockstore.cwl' to 'file:///home/ubuntu/cgpmap/Dockstore.cwl'
Tool definition failed validation:
Syntax error while parsing a block mapping
  in "file:///home/ubuntu/cgpmap/Dockstore.cwl", line 71, column 5
did not find expected key
  in "file:///home/ubuntu/cgpmap/Dockstore.cwl", line 74, column 7

```

Courtesy of @keiranmraine (thanks!)

### Environment (Browser or OS and Dockstore version)

1.1

**Comment by denis-yuen** [comment]
Present in 1.1.1 on staging
