### ISSUE TITLE
Some of the UI cypress tests fail occasionally 

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#540]
I think these failures are due to the page not loading fast enough. We should see if mocha/cypress has a timeout/wait option or retry option.

**Comment by denis-yuen** [comment]
@agduncan94 makes sense, could you add an example or two of the kind of error that shows up so we can recognize/search for it when it occurs?

**Comment by agduncan94** [comment]
https://travis-ci.org/ga4gh/dockstore-ui/jobs/183375643

**Comment by denis-yuen** [comment]
```
  1) Dockstore Tool Details Change tab to labels:

     CypressError: Timed out retrying: cy.click() failed because this element is not visible:

<li ng-class="{active: active, disabled: disabled}" active="activeTabs[1]" id="labelsTab" class="ng-scope ng-isolate-scope">...</li>

This element is not visible because it's parent: <div.row.ng-hide> has CSS property: 'display: none'

Fix this problem, or use {force: true} to disable error checking.

https://on.cypress.io/element-cannot-be-interacted-with

      at Object.cypressErr (http://localhost:9000/__cypress/static/js/cypress.js:5712:15)

      at Object.throwErr (http://localhost:9000/__cypress/static/js/cypress.js:5677:22)

      at Object.throwErrByPath (http://localhost:9000/__cypress/static/js/cypress.js:5704:21)

      at $Cy._retry (http://localhost:9000/__cypress/static/js/cypress.js:6635:26)

      at getCoords (http://localhost:9000/__cypress/static/js/cypress.js:7397:34)

      at $Cy.retry (http://localhost:9000/__cypress/static/js/cypress.js:7388:26)

      at http://localhost:9000/__cypress/static/js/cypress.js:6647:23

      at tryCatcher (http://localhost:9000/__cypress/static/js/vendor.js:42844:31)

      at Promise._settlePromiseFromHandler (http://localhost:9000/__cypress/static/js/vendor.js:40979:31)

      at Promise._settlePromiseAt (http://localhost:9000/__cypress/static/js/vendor.js:41055:18)

      at Promise._settlePromises (http://localhost:9000/__cypress/static/js/vendor.js:41171:14)

      at Async._drainQueue (http://localhost:9000/__cypress/static/js/vendor.js:38538:16)

      at Async._drainQueues (http://localhost:9000/__cypress/static/js/vendor.js:38548:10)

      at MutationObserver.Async.drainQueues (http://localhost:9000/__cypress/static/js/vendor.js:38376:14)

  2) Dockstore Tool Details Change tab to versions:

     CypressError: Timed out retrying: cy.click() failed because this element is not visible:

<li ng-class="{active: active, disabled: disabled}" active="activeTabs[2]" id="versionsTab" class="ng-scope ng-isolate-scope">...</li>

This element is not visible because it's parent: <div.row.ng-hide> has CSS property: 'display: none'

Fix this problem, or use {force: true} to disable error checking.

https://on.cypress.io/element-cannot-be-interacted-with

      at Object.cypressErr (http://localhost:9000/__cypress/static/js/cypress.js:5712:15)

      at Object.throwErr (http://localhost:9000/__cypress/static/js/cypress.js:5677:22)

      at Object.throwErrByPath (http://localhost:9000/__cypress/static/js/cypress.js:5704:21)

      at $Cy._retry (http://localhost:9000/__cypress/static/js/cypress.js:6635:26)

      at getCoords (http://localhost:9000/__cypress/static/js/cypress.js:7397:34)

      at $Cy.retry (http://localhost:9000/__cypress/static/js/cypress.js:7388:26)

      at http://localhost:9000/__cypress/static/js/cypress.js:6647:23

      at tryCatcher (http://localhost:9000/__cypress/static/js/vendor.js:42844:31)

      at Promise._settlePromiseFromHandler (http://localhost:9000/__cypress/static/js/vendor.js:40979:31)

      at Promise._settlePromiseAt (http://localhost:9000/__cypress/static/js/vendor.js:41055:18)

      at Promise._settlePromises (http://localhost:9000/__cypress/static/js/vendor.js:41171:14)

      at Async._drainQueue (http://localhost:9000/__cypress/static/js/vendor.js:38538:16)

      at Async._drainQueues (http://localhost:9000/__cypress/static/js/vendor.js:38548:10)

      at MutationObserver.Async.drainQueues (http://localhost:9000/__cypress/static/js/vendor.js:38376:14)

  3) Dockstore Tool Details Change tab to files "before each" hook for "Should have Dockerfile tab selected":

     CypressError: Timed out retrying: cy.click() failed because this element is not visible:

<li ng-class="{active: active, disabled: disabled}" active="activeTabs[3]" id="filesTab" class="ng-scope ng-isolate-scope">...</li>

This element is not visible because it's parent: <div.row.ng-hide> has CSS property: 'display: none'

Fix this problem, or use {force: true} to disable error checking.

https://on.cypress.io/element-cannot-be-interacted-with

Because this error occured during a 'before each' hook we are skipping the remaining tests in the current suite: 'Change tab to files'

      at Object.cypressErr (http://localhost:9000/__cypress/static/js/cypress.js:5712:15)

      at Object.throwErr (http://localhost:9000/__cypress/static/js/cypress.js:5677:22)

      at Object.throwErrByPath (http://localhost:9000/__cypress/static/js/cypress.js:5704:21)

      at $Cy._retry (http://localhost:9000/__cypress/static/js/cypress.js:6635:26)

      at getCoords (http://localhost:9000/__cypress/static/js/cypress.js:7397:34)

      at $Cy.retry (http://localhost:9000/__cypress/static/js/cypress.js:7388:26)

      at http://localhost:9000/__cypress/static/js/cypress.js:6647:23

      at tryCatcher (http://localhost:9000/__cypress/static/js/vendor.js:42844:31)

      at Promise._settlePromiseFromHandler (http://localhost:9000/__cypress/static/js/vendor.js:40979:31)

      at Promise._settlePromiseAt (http://localhost:9000/__cypress/static/js/vendor.js:41055:18)

      at Promise._settlePromises (http://localhost:9000/__cypress/static/js/vendor.js:41171:14)

      at Async._drainQueue (http://localhost:9000/__cypress/static/js/vendor.js:38538:16)

      at Async._drainQueues (http://localhost:9000/__cypress/static/js/vendor.js:38548:10)

      at MutationObserver.Async.drainQueues (http://localhost:9000/__cypress/static/js/vendor.js:38376:14)

  4) Dockstore tool search page Select a tool Should have two tools (and a hidden row):

     CypressError: Timed out retrying: Not enough elements found. Found '2', expected '3'.

      at Object.cypressErr (http://localhost:9000/__cypress/static/js/cypress.js:5712:15)

      at Object.throwErr (http://localhost:9000/__cypress/static/js/cypress.js:5677:22)

      at Object.throwErrByPath (http://localhost:9000/__cypress/static/js/cypress.js:5704:21)

      at $Cy._retry (http://localhost:9000/__cypress/static/js/cypress.js:6635:26)

      at http://localhost:9000/__cypress/static/js/cypress.js:8769:28

      at tryCatcher (http://localhost:9000/__cypress/static/js/vendor.js:42844:31)

      at Promise._settlePromiseFromHandler (http://localhost:9000/__cypress/static/js/vendor.js:40979:31)

      at Promise._settlePromiseAt (http://localhost:9000/__cypress/static/js/vendor.js:41055:18)

      at Promise._settlePromises (http://localhost:9000/__cypress/static/js/vendor.js:41171:14)

      at Async._drainQueue (http://localhost:9000/__cypress/static/js/vendor.js:38538:16)

      at Async._drainQueues (http://localhost:9000/__cypress/static/js/vendor.js:38548:10)

      at MutationObserver.Async.drainQueues (http://localhost:9000/__cypress/static/js/vendor.js:38376:14)

  5) Dockstore tool search page Select a tool Select dockstore-tool-imports:

     CypressError: Timed out retrying: expected '<h3#tool-path.ng-binding>' to contain 'quay.io/dockstoretestuser2/dockstore-tool-imports '

      at Object.cypressErr (http://localhost:9000/__cypress/static/js/cypress.js:5712:15)

      at Object.throwErr (http://localhost:9000/__cypress/static/js/cypress.js:5677:22)

      at Object.throwErrByPath (http://localhost:9000/__cypress/static/js/cypress.js:5704:21)

      at $Cy._retry (http://localhost:9000/__cypress/static/js/cypress.js:6635:26)

      at http://localhost:9000/__cypress/static/js/cypress.js:8769:28

      at tryCatcher (http://localhost:9000/__cypress/static/js/vendor.js:42844:31)

      at Promise._settlePromiseFromHandler (http://localhost:9000/__cypress/static/js/vendor.js:40979:31)

      at Promise._settlePromiseAt (http://localhost:9000/__cypress/static/js/vendor.js:41055:18)

      at Promise._settlePromises (http://localhost:9000/__cypress/static/js/vendor.js:41171:14)

      at Async._drainQueue (http://localhost:9000/__cypress/static/js/vendor.js:38538:16)

      at Async._drainQueues (http://localhost:9000/__cypress/static/js/vendor.js:38548:10)

      at MutationObserver.Async.drainQueues (http://localhost:9000/__cypress/static/js/vendor.js:38376:14)
```

**Comment by denis-yuen** [comment]
Still a thing? Otherwise, close

**Comment by agduncan94** [comment]
I think this is from UI1 so I don't think it is an issue.
