### ISSUE TITLE
Downloading ICGC file gives invalid filename because of 'icgc:'

### ISSUE THREAD

**Issue by jmonlong** [ga4gh/dockstore#587]
## Bug Report

I'm getting an error when dockstore uses the ICGC Storage Client to download an input file in the Collab cloud. 

### Expected behaviour

Specifying a BAM file in the input json file with:

```
"path": "icgc:05a6c15a-148c-5d20-a13d-f0d2702b15e4"
```

`dockstore` downloads the file with object id *05a6c15a-148c-5d20-a13d-f0d2702b15e4* and uses it as input, following the `Dockstore.cwl` file.

### Actual behaviour

The BAM file is downloaded but it seems like the `:` in the filename breaks `dockstore`.

I get `Invalid filename: 'icgc:05a6c15a-148c-5d20-a13d-f0d2702b15e4' contains illegal characters`. `icgc:05a6c15a-148c-5d20-a13d-f0d2702b15e4` exists and seems to be the correct file.

Here is a log using `--debug`:

```
ubuntu@docktest:~$ dockstore tool launch --entry Dockstore.cwl --local-entry --json test.json --debug
17:31:09.145 [main] INFO  io.github.collaboratory.LauncherCWL - MAKING DIRECTORIES...
Creating directories for run of Dockstore launcher at: ./datastore//launcher-0816a90e-916b-44cd-a5b8-f8ce3a5097aa
17:31:09.157 [main] INFO  io.dockstore.common.Utilities - CMD: mkdir -p ./datastore//launcher-0816a90e-916b-44cd-a5b8-f8ce3a5097aa
17:31:09.210 [main] INFO  io.dockstore.common.Utilities - exit code: 0
17:31:09.211 [main] DEBUG io.dockstore.common.Utilities - stderr was: 
17:31:09.211 [main] DEBUG io.dockstore.common.Utilities - stdout was: 
17:31:09.211 [main] INFO  io.dockstore.common.Utilities - CMD: mkdir -p ./datastore//launcher-0816a90e-916b-44cd-a5b8-f8ce3a5097aa/configs
17:31:09.261 [main] INFO  io.dockstore.common.Utilities - exit code: 0
17:31:09.261 [main] DEBUG io.dockstore.common.Utilities - stderr was: 
17:31:09.262 [main] DEBUG io.dockstore.common.Utilities - stdout was: 
17:31:09.262 [main] INFO  io.dockstore.common.Utilities - CMD: mkdir -p ./datastore//launcher-0816a90e-916b-44cd-a5b8-f8ce3a5097aa/working
17:31:09.312 [main] INFO  io.dockstore.common.Utilities - exit code: 0
17:31:09.313 [main] DEBUG io.dockstore.common.Utilities - stderr was: 
17:31:09.313 [main] DEBUG io.dockstore.common.Utilities - stdout was: 
17:31:09.313 [main] INFO  io.dockstore.common.Utilities - CMD: mkdir -p ./datastore//launcher-0816a90e-916b-44cd-a5b8-f8ce3a5097aa/inputs
17:31:09.363 [main] INFO  io.dockstore.common.Utilities - exit code: 0
17:31:09.364 [main] DEBUG io.dockstore.common.Utilities - stderr was: 
17:31:09.364 [main] DEBUG io.dockstore.common.Utilities - stdout was: 
17:31:09.364 [main] INFO  io.dockstore.common.Utilities - CMD: mkdir -p ./datastore//launcher-0816a90e-916b-44cd-a5b8-f8ce3a5097aa/logs
17:31:09.415 [main] INFO  io.dockstore.common.Utilities - exit code: 0
17:31:09.415 [main] DEBUG io.dockstore.common.Utilities - stderr was: 
17:31:09.416 [main] DEBUG io.dockstore.common.Utilities - stdout was: 
17:31:09.416 [main] INFO  io.dockstore.common.Utilities - CMD: mkdir -p ./datastore//launcher-0816a90e-916b-44cd-a5b8-f8ce3a5097aa/outputs
17:31:09.467 [main] INFO  io.dockstore.common.Utilities - exit code: 0
17:31:09.467 [main] DEBUG io.dockstore.common.Utilities - stderr was: 
17:31:09.467 [main] DEBUG io.dockstore.common.Utilities - stdout was: 
Provisioning your input files to your local machine
17:31:09.469 [main] INFO  io.github.collaboratory.LauncherCWL - DOWNLOADING INPUT FILES...
17:31:09.471 [main] INFO  io.github.collaboratory.LauncherCWL - {"label": null, "secondaryFiles": null, "format": null, "streamable": null, "doc": "The BAM file used as input.", "id": "file:///home/ubuntu/Dockstore.cwl#bam_input", "inputBinding": {"loadContents": null, "position": null, "prefix": "-b", "separate": null, "itemSeparator": null, "valueFrom": null, "shellQuote": null}, "default": null, "type": "File"}
17:31:09.481 [main] INFO  io.github.collaboratory.LauncherCWL - ID: bam_input
17:31:09.482 [main] INFO  io.github.collaboratory.LauncherCWL - JSON: {bam_input={class=File, format=http://edamontology.org/format_2572, path=icgc:05a6c15a-148c-5d20-a13d-f0d2702b15e4}, klist_input={class=File, path=test-klist.txt}, ktag_output={class=File, path=s3://dockstoreTest/test-ktag-output.txt}}
17:31:09.484 [main] INFO  io.github.collaboratory.LauncherCWL - PATH TO DOWNLOAD FROM: icgc:05a6c15a-148c-5d20-a13d-f0d2702b15e4 FOR bam_input FOR bam_input
Downloading: #bam_input from icgc:05a6c15a-148c-5d20-a13d-f0d2702b15e4 into directory: /home/ubuntu/./datastore/launcher-0816a90e-916b-44cd-a5b8-f8ce3a5097aa/inputs/33b609b2-838c-46de-b9f5-31d760a8cf6b
17:31:09.484 [main] INFO  io.dockstore.common.Utilities - CMD: mkdir -p /home/ubuntu/./datastore/launcher-0816a90e-916b-44cd-a5b8-f8ce3a5097aa/inputs/33b609b2-838c-46de-b9f5-31d760a8cf6b
17:31:09.534 [main] INFO  io.dockstore.common.Utilities - exit code: 0
17:31:09.535 [main] DEBUG io.dockstore.common.Utilities - stderr was: 
17:31:09.535 [main] DEBUG io.dockstore.common.Utilities - stdout was: 
17:31:09.536 [main] INFO  io.dockstore.common.Utilities - CMD: /home/ubuntu/icgc-storage-client-1.0.23/bin/icgc-storage-client --quiet download --object-id 05a6c15a-148c-5d20-a13d-f0d2702b15e4 --output-dir /home/ubuntu/./datastore/launcher-0816a90e-916b-44cd-a5b8-f8ce3a5097aa/inputs/33b609b2-838c-46de-b9f5-31d760a8cf6b --output-layout id
17:33:57.235 [main] INFO  io.dockstore.common.Utilities - exit code: 0
Downloading...                                                                  .
--------------------------------------------------------------------------------
[1/2] Downloading object: 0b182cab-d83a-5017-8bcb-474f69cc1354 (PCAWG.b112f618-c81a-4639-b24a-6521ee527d31.TopHat2.v1.bam.bai)
--------------------------------------------------------------------------------
Restarting                                                                      
Finalizing...
Total execution time:        416.5 ms
Total bytes read    :       3,107,816
Total bytes written :               0
Verifying checksum...Done.                                                      
--------------------------------------------------------------------------------
[2/2] Downloading object: 05a6c15a-148c-5d20-a13d-f0d2702b15e4 (PCAWG.b112f618-c81a-4639-b24a-6521ee527d31.TopHat2.v1.bam)
--------------------------------------------------------------------------------
Restarting                                                                      
Finalizing...
Total execution time:       2.351 min
Total bytes read    :   3,841,386,551
Total bytes written :               0
Verifying checksum...Done.                                                      

17:33:57.238 [main] DEBUG io.dockstore.common.Utilities - stdout was: 
download path: /home/ubuntu/./datastore/launcher-0816a90e-916b-44cd-a5b8-f8ce3a5097aa/inputs/33b609b2-838c-46de-b9f5-31d760a8cf6b/05a6c15a-148c-5d20-a13d-f0d2702b15e4
17:33:57.243 [main] INFO  io.github.collaboratory.LauncherCWL - DOWNLOADED FILE: LOCAL: icgc:05a6c15a-148c-5d20-a13d-f0d2702b15e4 URL: icgc:05a6c15a-148c-5d20-a13d-f0d2702b15e4
17:33:57.244 [main] INFO  io.github.collaboratory.LauncherCWL - {"label": null, "secondaryFiles": null, "format": null, "streamable": null, "doc": "A file with the list of khmer to consider.", "id": "file:///home/ubuntu/Dockstore.cwl#klist_input", "inputBinding": {"loadContents": null, "position": null, "prefix": "-k", "separate": null, "itemSeparator": null, "valueFrom": null, "shellQuote": null}, "default": null, "type": "File"}
17:33:57.244 [main] INFO  io.github.collaboratory.LauncherCWL - ID: klist_input
17:33:57.244 [main] INFO  io.github.collaboratory.LauncherCWL - JSON: {bam_input={class=File, format=http://edamontology.org/format_2572, path=icgc:05a6c15a-148c-5d20-a13d-f0d2702b15e4}, klist_input={class=File, path=test-klist.txt}, ktag_output={class=File, path=s3://dockstoreTest/test-ktag-output.txt}}
17:33:57.244 [main] INFO  io.github.collaboratory.LauncherCWL - PATH TO DOWNLOAD FROM: test-klist.txt FOR klist_input FOR klist_input
Downloading: #klist_input from test-klist.txt into directory: /home/ubuntu/./datastore/launcher-0816a90e-916b-44cd-a5b8-f8ce3a5097aa/inputs/1b5393e0-ab51-4d86-a73f-e5695fc3e35e
17:33:57.244 [main] INFO  io.dockstore.common.Utilities - CMD: mkdir -p /home/ubuntu/./datastore/launcher-0816a90e-916b-44cd-a5b8-f8ce3a5097aa/inputs/1b5393e0-ab51-4d86-a73f-e5695fc3e35e
17:33:57.295 [main] INFO  io.dockstore.common.Utilities - exit code: 0
17:33:57.296 [main] DEBUG io.dockstore.common.Utilities - stderr was: 
17:33:57.296 [main] DEBUG io.dockstore.common.Utilities - stdout was: 
17:33:57.296 [main] INFO  i.d.common.FileProvisioning$PathInfo - Invalid or local path specified for CWL pre-processor values: test-klist.txt
17:33:57.302 [main] INFO  io.github.collaboratory.LauncherCWL - DOWNLOADED FILE: LOCAL: test-klist.txt URL: test-klist.txt
17:33:57.302 [main] INFO  io.github.collaboratory.LauncherCWL - PREPPING UPLOADS...
17:33:57.302 [main] INFO  io.github.collaboratory.LauncherCWL - {"label": null, "secondaryFiles": null, "format": null, "streamable": null, "doc": "A file with the tag for each read (with at least one khmer present).", "id": "file:///home/ubuntu/Dockstore.cwl#ktag_output", "outputBinding": {"glob": "ktag_output.txt", "loadContents": null, "outputEval": null}, "type": "File"}
17:33:57.302 [main] INFO  io.github.collaboratory.LauncherCWL - ID: ktag_output
17:33:57.302 [main] INFO  io.github.collaboratory.LauncherCWL - JSON: {bam_input={class=File, format=http://edamontology.org/format_2572, path=icgc:05a6c15a-148c-5d20-a13d-f0d2702b15e4}, klist_input={class=File, path=test-klist.txt}, ktag_output={class=File, path=s3://dockstoreTest/test-ktag-output.txt}}
17:33:57.302 [main] INFO  io.github.collaboratory.LauncherCWL - PATH TO UPLOAD TO: s3://dockstoreTest/test-ktag-output.txt FOR ktag_output
17:33:57.302 [main] INFO  io.dockstore.common.Utilities - CMD: mkdir -p /home/ubuntu/./datastore/launcher-0816a90e-916b-44cd-a5b8-f8ce3a5097aa/outputs
17:33:57.353 [main] INFO  io.dockstore.common.Utilities - exit code: 0
17:33:57.353 [main] DEBUG io.dockstore.common.Utilities - stderr was: 
17:33:57.353 [main] DEBUG io.dockstore.common.Utilities - stdout was: 
17:33:57.353 [main] INFO  io.github.collaboratory.LauncherCWL - UPLOAD FILE: LOCAL: ktag_output URL: s3://dockstoreTest/test-ktag-output.txt
17:33:57.354 [main] INFO  io.github.collaboratory.LauncherCWL - PATH: icgc:05a6c15a-148c-5d20-a13d-f0d2702b15e4 PARAM_NAME: bam_input
17:33:57.354 [main] INFO  io.github.collaboratory.LauncherCWL - NEW FULL PATH: /home/ubuntu/./datastore/launcher-0816a90e-916b-44cd-a5b8-f8ce3a5097aa/inputs/33b609b2-838c-46de-b9f5-31d760a8cf6b/icgc:05a6c15a-148c-5d20-a13d-f0d2702b15e4
17:33:57.355 [main] INFO  io.github.collaboratory.LauncherCWL - PATH: test-klist.txt PARAM_NAME: klist_input
17:33:57.355 [main] INFO  io.github.collaboratory.LauncherCWL - NEW FULL PATH: /home/ubuntu/./datastore/launcher-0816a90e-916b-44cd-a5b8-f8ce3a5097aa/inputs/1b5393e0-ab51-4d86-a73f-e5695fc3e35e/test-klist.txt
17:33:57.355 [main] INFO  io.github.collaboratory.LauncherCWL - PATH: s3://dockstoreTest/test-ktag-output.txt PARAM_NAME: ktag_output
17:33:57.356 [main] INFO  io.github.collaboratory.LauncherCWL - NEW FULL PATH: /home/ubuntu/./datastore/launcher-0816a90e-916b-44cd-a5b8-f8ce3a5097aa/outputs/ktag_output
Calling out to cwltool to run your tool
Executing: cwltool --enable-dev --non-strict --outdir /home/ubuntu/./datastore/launcher-0816a90e-916b-44cd-a5b8-f8ce3a5097aa/outputs/ --tmpdir-prefix /home/ubuntu/./datastore/launcher-0816a90e-916b-44cd-a5b8-f8ce3a5097aa/working/ /home/ubuntu/Dockstore.cwl /home/ubuntu/./datastore/launcher-0816a90e-916b-44cd-a5b8-f8ce3a5097aa/workflow_params.json
17:33:57.387 [main] INFO  io.dockstore.common.Utilities - CMD: cwltool --enable-dev --non-strict --outdir /home/ubuntu/./datastore/launcher-0816a90e-916b-44cd-a5b8-f8ce3a5097aa/outputs/ --tmpdir-prefix /home/ubuntu/./datastore/launcher-0816a90e-916b-44cd-a5b8-f8ce3a5097aa/working/ /home/ubuntu/Dockstore.cwl /home/ubuntu/./datastore/launcher-0816a90e-916b-44cd-a5b8-f8ce3a5097aa/workflow_params.json
/usr/local/bin/cwltool 1.0.20161114152756
Resolved '/home/ubuntu/Dockstore.cwl' to 'file:///home/ubuntu/Dockstore.cwl'
Workflow error, try again with --debug for more information:
  Invalid filename: 'icgc:05a6c15a-148c-5d20-a13d-f0d2702b15e4' contains illegal characters
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.access$200(DefaultExecutor.java:48)
	at org.apache.commons.exec.DefaultExecutor$1.run(DefaultExecutor.java:200)
	at java.lang.Thread.run(Thread.java:745)
17:33:58.189 [main] INFO  io.dockstore.common.Utilities - exit code: 1
17:33:58.190 [main] DEBUG io.dockstore.common.Utilities - stderr was: /usr/local/bin/cwltool 1.0.20161114152756
Resolved '/home/ubuntu/Dockstore.cwl' to 'file:///home/ubuntu/Dockstore.cwl'
Workflow error, try again with --debug for more information:
  Invalid filename: 'icgc:05a6c15a-148c-5d20-a13d-f0d2702b15e4' contains illegal characters

17:33:58.190 [main] DEBUG io.dockstore.common.Utilities - stdout was: 
java.lang.RuntimeException: problems running command: cwltool --enable-dev --non-strict --outdir /home/ubuntu/./datastore/launcher-0816a90e-916b-44cd-a5b8-f8ce3a5097aa/outputs/ --tmpdir-prefix /home/ubuntu/./datastore/launcher-0816a90e-916b-44cd-a5b8-f8ce3a5097aa/working/ /home/ubuntu/Dockstore.cwl /home/ubuntu/./datastore/launcher-0816a90e-916b-44cd-a5b8-f8ce3a5097aa/workflow_params.json
	at io.dockstore.common.Utilities.executeCommand(Utilities.java:107)
	at io.dockstore.common.Utilities.executeCommand(Utilities.java:62)
	at io.github.collaboratory.LauncherCWL.runCWLCommand(LauncherCWL.java:460)
	at io.github.collaboratory.LauncherCWL.run(LauncherCWL.java:197)
	at io.dockstore.client.cli.nested.AbstractEntryClient.handleCWLLaunch(AbstractEntryClient.java:1028)
	at io.dockstore.client.cli.nested.AbstractEntryClient.launchCwl(AbstractEntryClient.java:968)
	at io.dockstore.client.cli.nested.AbstractEntryClient.checkEntryFile(AbstractEntryClient.java:857)
	at io.dockstore.client.cli.nested.AbstractEntryClient.launch(AbstractEntryClient.java:930)
	at io.dockstore.client.cli.nested.AbstractEntryClient.processEntryCommands(AbstractEntryClient.java:247)
	at io.dockstore.client.cli.Client.run(Client.java:704)
	at io.dockstore.client.cli.Client.main(Client.java:796)
Caused by: org.apache.commons.exec.ExecuteException: problems running command: cwltool --enable-dev --non-strict --outdir /home/ubuntu/./datastore/launcher-0816a90e-916b-44cd-a5b8-f8ce3a5097aa/outputs/ --tmpdir-prefix /home/ubuntu/./datastore/launcher-0816a90e-916b-44cd-a5b8-f8ce3a5097aa/working/ /home/ubuntu/Dockstore.cwl /home/ubuntu/./datastore/launcher-0816a90e-916b-44cd-a5b8-f8ce3a5097aa/workflow_params.json (Exit value: 1)
	at io.dockstore.common.Utilities.executeCommand(Utilities.java:103)
	... 10 more
```

### Steps to reproduce the behaviour 

[GitHub with tool/dockerfile/dockstore](https://github.com/jmonlong/dockstore-ktag) although I don't think it's a problem with the tool as it breaks before trying to run it.

The input json file is the same as in the GitHub repo except for the *path* parameter of *bam_input* which is:

```
"path": "icgc:05a6c15a-148c-5d20-a13d-f0d2702b15e4"
```

### Environment 

I use dockstore version 1.1.2 and the recommended CWL version (1.0.20161114152756). I'm running this in the Collaboratory cloud.

**Comment by denis-yuen** [comment]
Fix is in production as of 1.1.5
