### ISSUE TITLE
GUI allows workflow name to be optional

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#593]
### Expected behaviour

The GUI will disallow a blank workflow name if it is required 

### Actual behaviour

The GUI allows one and then you get 
```
ERROR [2017-02-16 16:14:39,826] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: 1cbed29a9877d6f0
! java.lang.NullPointerException: null
! at io.dockstore.webservice.resources.WorkflowResource.manualRegister(WorkflowResource.java:848)
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
! at java.lang.reflect.Method.invoke(Method.java:497)
...
! at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:136)
! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:671)
! at org.eclipse.jetty.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:589)
! at java.lang.Thread.run(Thread.java:745)
0:0:0:0:0:0:0:1 - - [16/Feb/2017:16:14:39 +0000] "POST /workflows/manualRegister?defaultWorkflowPath=%2FDockstore.cwl&descriptorType=cwl&workflowPath=denis-yuen%2Fhello-world-workflow&workflowRegistry=GitHub HTTP/1.1" 500 110 "http://localhost:9000/my-workflows" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/55.0.2883.87 Chrome/55.0.2883.87 Safari/537.36" 9
```
on the webservice

### Steps to reproduce the behaviour 

Register a workflow with a newly spun up webservice+UI. 
Make sure that you register the same workflow twice to get the error. For example, register 
denis-yuen/hello-dockstore-workflow twice without adding a workflow name

### Environment (Browser or OS and Dockstore version)

Develop as of 2017-02-16

**Comment by denis-yuen** [comment]
Check if a workflow already exists and if it does, display a helpful error message rather than a 500
(By comparison, trying to add the same tool twice is more helpful displaying "[HTTP 400] Bad Request: Tool quay.io/denis_yuen/test1 already exists."

**Comment by denis-yuen** [comment]
Looks good on staging.dockstore.org
Message now displays 
```
 The webservice encountered an error trying to create this workflow, please ensure that the workflow attributes are valid and the same image has not already been registered.
[HTTP 400] Bad Request: A workflow with the same path and name already exists.
```
