### ISSUE TITLE
Build issue - docker pull fails

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#650]
## Bug Report

Another build issue that can fail a build without any code issues on our side

### Actual behaviour

We saw a build fail due to this:

```
Calling out to cwltool to run your tool
Executing: cwltool --enable-dev --non-strict --outdir /home/travis/build/ga4gh/dockstore/dockstore-integration-testing/./datastore/launcher-40213ee1-0126-4d21-95bd-e992be92d90e/outputs/ --tmpdir-prefix /home/travis/build/ga4gh/dockstore/dockstore-integration-testing/./datastore/launcher-40213ee1-0126-4d21-95bd-e992be92d90e/tmp/ --tmp-outdir-prefix /home/travis/build/ga4gh/dockstore/dockstore-integration-testing/./datastore/launcher-40213ee1-0126-4d21-95bd-e992be92d90e/working/ /home/travis/build/ga4gh/dockstore/dockstore-integration-testing/target/test-classes/arrays.cwl /home/travis/build/ga4gh/dockstore/dockstore-integration-testing/./datastore/launcher-40213ee1-0126-4d21-95bd-e992be92d90e/workflow_params.json
/home/travis/.local/bin/cwltool 1.0.20170217172322
Resolved '/home/travis/build/ga4gh/dockstore/dockstore-integration-testing/target/test-classes/arrays.cwl' to 'file:///home/travis/build/ga4gh/dockstore/dockstore-integration-testing/target/test-classes/arrays.cwl'
['docker', 'pull', 'quay.io/collaboratory/dockstore-tool-linux-sort']
Using default tag: latest
Error response from daemon: Get https://quay.io/v2/collaboratory/dockstore-tool-linux-sort/manifests/latest: Get https://quay.io/v2/auth?scope=repository%3Acollaboratory%2Fdockstore-tool-linux-sort%3Apull&service=quay.io: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Got workflow error
Traceback (most recent call last):
  File "/home/travis/.local/lib/python2.7/site-packages/cwltool/main.py", line 224, in single_job_executor
    r.run(**kwargs)
  File "/home/travis/.local/lib/python2.7/site-packages/cwltool/job.py", line 140, in run
    img_id = docker.get_from_requirements(docker_req, docker_is_req, pull_image)
  File "/home/travis/.local/lib/python2.7/site-packages/cwltool/docker.py", line 105, in get_from_requirements
    if get_image(r, pull_image, dry_run):
  File "/home/travis/.local/lib/python2.7/site-packages/cwltool/docker.py", line 43, in get_image
    subprocess.check_call(cmd, stdout=sys.stderr)
  File "/opt/python/2.7.12/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['docker', 'pull', 'quay.io/collaboratory/dockstore-tool-linux-sort']' returned non-zero exit status 1
Workflow error, try again with --debug for more information:
Command '['docker', 'pull', 'quay.io/collaboratory/dockstore-tool-linux-sort']' returned non-zero exit status 1
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.access$200(DefaultExecutor.java:48)
	at org.apache.commons.exec.DefaultExecutor$1.run(DefaultExecutor.java:200)
	at java.lang.Thread.run(Thread.java:745)
java.lang.RuntimeException: problems running command
```

See whether there is a way to cache Docker images on quay.io

**Comment by denis-yuen** [comment]
Listed in https://docs.travis-ci.com/user/caching/#Things-not-to-cache
