### ISSUE TITLE
Setting default branch is broken in  1.2.0-beta.0

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#660]
### Expected behaviour

Clicking on a Git Reference will refresh and save the default as in production

### Actual behaviour

Clicking on a Git Reference results in no change

**Comment by denis-yuen** [comment]
Error on the server side 
```
ERROR [2017-04-06 16:30:33,696] io.dropwizard.jersey.jackson.JsonProcessingExceptionMapper: Unable to serialize or deserialize the specific type
! com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of io.dockstore.webservice.core.Entry, problem: abstract types either need to be mapped to concrete types, have custom des
erializer, or be instantiated with additional type information
!  at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@68abcf55; line: 1, column: 1519] (through reference chain: io.dockstore.webservice.core.Tool["users"]-
>java.util.HashSet[2]->io.dockstore.webservice.core.User["starredEntries"]->java.util.HashSet[0])
! at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:256)
! at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1007)
! at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserialize(AbstractDeserializer.java:150)
! at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:277)
! at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:249)
! at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
! at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
! at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:101)
! at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:156)
! at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:277)
! at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:249)
! at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
! at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:490)
! at com.fasterxml.jackson.module.afterburner.deser.SettableObjectMethodProperty.deserializeAndSet(SettableObjectMethodProperty.java:55)
! at com.fasterxml.jackson.module.afterburner.deser.SuperSonicBeanDeserializer.deserialize(SuperSonicBeanDeserializer.java:156)
! at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1536)
! at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:944)
! at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:811)
! at io.dropwizard.jersey.jackson.JacksonMessageBodyProvider.readFrom(JacksonMessageBodyProvider.java:54)

```

**Comment by denis-yuen** [comment]
Works on developer version. 
Looks like a database migration issue

**Comment by denis-yuen** [comment]
Works with a copy of the production database, looks like only a staging database issue
