### ISSUE TITLE
check for java 8, documentation and CLI

### ISSUE THREAD

**Issue by mr-c** [ga4gh/dockstore#76]
OS: Debian unstable 'sid'

```
mcrusoe@mrcdev:~/src$ dockstore
Exception in thread "main" java.lang.UnsupportedClassVersionError: io/dockstore/client/cli/Client : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
mcrusoe@mrcdev:~/src$ java -version
java version "1.7.0_91"
OpenJDK Runtime Environment (IcedTea 2.6.3) (7u91-2.6.3-2)
OpenJDK 64-Bit Server VM (build 24.91-b01, mixed mode)
```

**Comment by mr-c** [comment]
Fixed via

```
sudo apt-get install openjdk-8-jre-headless
sudo update-java-alternatives -s java-1.8.0-openjdk
```

**Comment by denis-yuen** [comment]
Yep, we definitely use Java 8 functionality and that needs to be better explained in the documentation and a better error message for the tool.
