### ISSUE TITLE
dockstore refresh error

### ISSUE THREAD

**Issue by mr-c** [ga4gh/dockstore#77]
```
mcrusoe@mrcdev:~/src$ dockstore refresh
Exception: io.swagger.client.ApiException: {"code":500,"message":"There was an error processing your request. It has been logged (ID 959bd0e62fcd7335)."}
```

**Comment by denis-yuen** [comment]
@oicr-vchung Do you mind grabbing the error on the web service side and attaching it to this ticket? Thanks

**Comment by oicr-vchung** [comment]
```
INFO  [2015-12-17 15:42:03,196] org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: Session Metrics {
    26451 nanoseconds spent acquiring 1 JDBC connections;
    0 nanoseconds spent releasing 0 JDBC connections;
    14337 nanoseconds spent preparing 1 JDBC statements;
    358770 nanoseconds spent executing 1 JDBC statements;
    0 nanoseconds spent executing 0 JDBC batches;
    0 nanoseconds spent performing 0 L2C puts;
    0 nanoseconds spent performing 0 L2C hits;
    0 nanoseconds spent performing 0 L2C misses;
    49725 nanoseconds spent executing 1 flushes (flushing a total of 1 entities and 2 collections);
    0 nanoseconds spent executing 0 partial-flushes (flushing a total of 0 entities and 0 collections)
}
23.253.34.202 - - [17/Dec/2015:15:42:03 +0000] "GET /users/user HTTP/1.1" 200 75 "-" "Java-Swagger" 2
INFO  [2015-12-17 15:42:03,491] io.dockstore.webservice.Helper: WARNING: BITBUCKET token not found!
INFO  [2015-12-17 15:42:03,500] org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: Session Metrics {
    26363 nanoseconds spent acquiring 1 JDBC connections;
    0 nanoseconds spent releasing 0 JDBC connections;
    73486 nanoseconds spent preparing 4 JDBC statements;
    1161811 nanoseconds spent executing 4 JDBC statements;
    0 nanoseconds spent executing 0 JDBC batches;
    0 nanoseconds spent performing 0 L2C puts;
    0 nanoseconds spent performing 0 L2C hits;
    0 nanoseconds spent performing 0 L2C misses;
    0 nanoseconds spent executing 0 flushes (flushing a total of 0 entities and 0 collections);
    75057 nanoseconds spent executing 2 partial-flushes (flushing a total of 2 entities and 2 collections)
}
ERROR [2015-12-17 15:42:03,501] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: 959bd0e62fcd7335
! java.lang.NullPointerException: null
! at io.dockstore.webservice.helpers.QuayImageRegistry.<init>(QuayImageRegistry.java:55) ~[dockstore-webservice-0.2.1.jar:0.2.1]
! at io.dockstore.webservice.helpers.ImageRegistryFactory.createImageRegistry(ImageRegistryFactory.java:42) ~[dockstore-webservice-0.2.1.jar:0.2.1]
! at io.dockstore.webservice.helpers.ImageRegistryFactory.getAllRegistries(ImageRegistryFactory.java:35) ~[dockstore-webservice-0.2.1.jar:0.2.1]
! at io.dockstore.webservice.Helper.refresh(Helper.java:473) ~[dockstore-webservice-0.2.1.jar:0.2.1]
! at io.dockstore.webservice.resources.UserResource.refresh(UserResource.java:405) ~[dockstore-webservice-0.2.1.jar:0.2.1]
! at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_66]
! at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_66]
! at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_66]
! at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_66]
! at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81) ~[dockstore-webservice-0.2.1.jar:0.2.1]
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144) ~[dockstore-webservice-0.2.1.jar:0.2.1]
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161) ~[dockstore-webservice-0.2.1.jar:0.2.1]
! at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$TypeOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:205) ~[dockstore-webservice-0.2.1.jar:0.2.1]
! at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99) ~[dockstore-webservice-0.2.1.jar:0.2.1]
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389) ~[dockstore-webservice-0.2.1.jar:0.2.1]
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347) ~[dockstore-webservice-0.2.1.jar:0.2.1]
! at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102) ~[dockstore-webservice-0.2.1.jar:0.2.1]
! at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:309) ~[dockstore-webservice-0.2.1.jar:0.2.1]
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271) [dockstore-webservice-0.2.1.jar:0.2.1]
! at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267) [dockstore-webservice-0.2.1.jar:0.2.1]
! at org.glassfish.jersey.internal.Errors.process(Errors.java:315) [dockstore-webservice-0.2.1.jar:0.2.1]
! at org.glassfish.jersey.internal.Errors.process(Errors.java:297) [dockstore-webservice-0.2.1.jar:0.2.1]
! at org.glassfish.jersey.internal.Errors.process(Errors.java:267) [dockstore-webservice-0.2.1.jar:0.2.1]
! at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317) [dockstore-webservice-0.2.1.jar:0.2.1]
! at org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:292) [dockstore-webservice-0.2.1.jar:0.2.1]
! at org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1139) [dockstore-webservice-0.2.1.jar:0.2.1]
! at org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:460) [dockstore-webservice-0.2.1.jar:0.2.1]
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:386) [dockstore-webservice-0.2.1.jar:0.2.1]
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:334) [dockstore-webservice-0.2.1.jar:0.2.1]
! at org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221) [dockstore-webservice-0.2.1.jar:0.2.1]
! at io.dropwizard.jetty.NonblockingServletHolder.handle(NonblockingServletHolder.java:49) [dockstore-webservice-0.2.1.jar:0.2.1]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1669) [dockstore-webservice-0.2.1.jar:0.2.1]
! at org.eclipse.jetty.servlets.UserAgentFilter.doFilter(UserAgentFilter.java:83) [dockstore-webservice-0.2.1.jar:0.2.1]
! at org.eclipse.jetty.servlets.GzipFilter.doFilter(GzipFilter.java:364) [dockstore-webservice-0.2.1.jar:0.2.1]
! at io.dropwizard.jetty.BiDiGzipFilter.doFilter(BiDiGzipFilter.java:134) [dockstore-webservice-0.2.1.jar:0.2.1]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [dockstore-webservice-0.2.1.jar:0.2.1]
! at org.eclipse.jetty.servlets.CrossOriginFilter.handle(CrossOriginFilter.java:259) [dockstore-webservice-0.2.1.jar:0.2.1]
! at org.eclipse.jetty.servlets.CrossOriginFilter.doFilter(CrossOriginFilter.java:222) [dockstore-webservice-0.2.1.jar:0.2.1]
! at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1652) [dockstore-webservice-0.2.1.jar:0.2.1]
! at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585) [dockstore-webservice-0.2.1.jar:0.2.1]
! at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1127) [dockstore-webservice-0.2.1.jar:0.2.1]
! at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515) [dockstore-webservice-0.2.1.jar:0.2.1]
! at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1061) [dockstore-webservice-0.2.1.jar:0.2.1]
! at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141) [dockstore-webservice-0.2.1.jar:0.2.1]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [dockstore-webservice-0.2.1.jar:0.2.1]
! at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:240) [dockstore-webservice-0.2.1.jar:0.2.1]
! at io.dropwizard.jetty.RoutingHandler.handle(RoutingHandler.java:51) [dockstore-webservice-0.2.1.jar:0.2.1]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [dockstore-webservice-0.2.1.jar:0.2.1]
! at org.eclipse.jetty.server.handler.RequestLogHandler.handle(RequestLogHandler.java:95) [dockstore-webservice-0.2.1.jar:0.2.1]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [dockstore-webservice-0.2.1.jar:0.2.1]
! at org.eclipse.jetty.server.handler.StatisticsHandler.handle(StatisticsHandler.java:159) [dockstore-webservice-0.2.1.jar:0.2.1]
! at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97) [dockstore-webservice-0.2.1.jar:0.2.1]
! at org.eclipse.jetty.server.Server.handle(Server.java:497) [dockstore-webservice-0.2.1.jar:0.2.1]
! at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:310) [dockstore-webservice-0.2.1.jar:0.2.1]
! at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:257) [dockstore-webservice-0.2.1.jar:0.2.1]
! at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540) [dockstore-webservice-0.2.1.jar:0.2.1]
! at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:635) [dockstore-webservice-0.2.1.jar:0.2.1]
! at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:555) [dockstore-webservice-0.2.1.jar:0.2.1]
! at java.lang.Thread.run(Thread.java:745) [na:1.8.0_66]
23.253.34.202 - - [17/Dec/2015:15:42:03 +0000] "GET /users/19/containers/refresh HTTP/1.1" 500 110 "-" "Java-Swagger" 24
```

**Comment by oicr-vchung** [comment]
@victoroicr believes this is because you did not register a Quay.io token before performing the refresh (Quay.io is the only supported service right now). This should have failed silently, instead of returning an error, so that will be fixed.

**Comment by mr-c** [comment]
Thanks!

Joi, 17 dec. 2015, 22:02, oicr-vchung <notifications@github.com> a scris:

> @victoroicr <https://github.com/victoroicr> believes this is because you
> did not register a Quay.io token before performing the refresh (Quay.io is
> the only supported service right now). This should have failed silently,
> instead of returning an error, so that will be fixed.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ga4gh/dockstore/issues/77#issuecomment-165566961>.
>
-- 
Michael R. Crusoe     CWL Community Engineer     crusoe@ucdavis.edu
<mcrusoe@msu.edu>
Common Workflow Language project    University of California, Davis
https://impactstory.org/MichaelRCrusoe http://twitter.com/biocrusoe

**Comment by victoroicr** [comment]
fixed
