### ISSUE TITLE
Format issue with certain workflows

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#782]
### Desired behaviour

Error message is 
```
$ dockstore workflow cwl --entry  Barski-lab/biowardrobe_chipseq_se 
Downloading Dockstore to /home/dyuen/.dockstore/self-installs/dockstore-client-1.2.3.jar now...
file:////home/dyuen/.m2/repository/io/dockstore/dockstore-client/1.2.3/dockstore-client-1.2.3-shaded.jar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 42.4M  100 42.4M    0     0   503M      0 --:--:-- --:--:-- --:--:--  503M
Exception in thread "main" java.util.MissingFormatArgumentException: Format specifier '%20c'
	at java.util.Formatter.format(Formatter.java:2519)
	at java.util.Formatter.format(Formatter.java:2455)
	at java.lang.String.format(String.java:2940)
	at io.dockstore.client.cli.ArgumentUtility.err(ArgumentUtility.java:55)
	at io.dockstore.client.cli.ArgumentUtility.exceptionMessage(ArgumentUtility.java:70)
	at io.dockstore.client.cli.Client.run(Client.java:757)
	at io.dockstore.client.cli.Client.main(Client.java:618)
```

Seems like an issue with the VM not properly distinguishing between method with one parameter and varargs and method with one parameter.

**Comment by denis-yuen** [comment]
This command is now functional from 1.2.4 and tested at staging.dockstore.org
