### ISSUE TITLE
Make file provisioning plugins compatible with whole directory copy

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#787]
### Desired behaviour

It should be possible to copy a whole directory at once as per CWL 1.0. 
Currently, these plug-ins will likely do something like the following
```
Calling on plugin io.dockstore.provision.S3Plugin$S3Provision to provision from /home/dyuen/temp/./datastore/launcher-a84ce197-f2fe-4739-8cc4-8909b0aa54f3/outputs/hello_world.cwl to s3://oicr.temp/ga4gh-dream2/hello_world_files/hello_world.cwl
[##################################################] 100%
Calling on plugin io.dockstore.provision.S3Plugin$S3Provision to provision from /home/dyuen/temp/./datastore/launcher-a84ce197-f2fe-4739-8cc4-8909b0aa54f3/outputs/hello_world_ref to s3://oicr.temp/ga4gh-dream2/hello_world_files/hello_world_ref
java.lang.RuntimeException: plugin threw an exception
16:22:11.726 [main] ERROR io.dockstore.common.FileProvisioning - plugin threw an exception
com.amazonaws.SdkClientException: Unable to calculate MD5 hash: /home/dyuen/temp/./datastore/launcher-a84ce197-f2fe-4739-8cc4-8909b0aa54f3/outputs/hello_world_ref (Is a directory)
	at com.amazonaws.services.s3.AmazonS3Client.putObject(AmazonS3Client.java:1614)
	at com.amazonaws.services.s3.transfer.internal.UploadCallable.uploadInOneChunk(UploadCallable.java:133)
	at com.amazonaws.services.s3.transfer.internal.UploadCallable.call(UploadCallable.java:125)
	at com.amazonaws.services.s3.transfer.internal.UploadMonitor.call(UploadMonitor.java:139)
```

**Comment by denis-yuen** [comment]
Completed with 1.2.4
