### ISSUE TITLE
Invalid ga4gh tool registry response

### ISSUE THREAD

**Issue by tetron** [ga4gh/dockstore#814]
## Bug Report

When requesting a list of tools, the `verified-source` field may be returned with a value of `null`.  However, the schema specifies that it must be a string.

### Expected behaviour

The return value should be a string to match the schema, or the schema needs to be updated so than `null` is allowed for that field.

### Actual behaviour

```
from bravado.client import SwaggerClient
client = SwaggerClient.from_url("https://dockstore.org:8443/swagger.json",
                                config={'use_models': False, 'validate_responses': True})
print client.GA4GH.toolsGet().result()
```

```
$ python tool_reg.py
Traceback (most recent call last):
  File "tool_reg.py", line 6, in <module>
    print client.GA4GH.toolsGet().result()
  File "build/bdist.linux-x86_64/egg/bravado/http_future.py", line 78, in result
  File "build/bdist.linux-x86_64/egg/bravado/http_future.py", line 116, in unmarshal_response
  File "build/bdist.linux-x86_64/egg/bravado_core/response.py", line 109, in unmarshal_response
  File "build/bdist.linux-x86_64/egg/bravado_core/validate.py", line 30, in validate_schema_object
  File "build/bdist.linux-x86_64/egg/bravado_core/validate.py", line 64, in validate_array
  File "/home/peter/work/ga4gh/workflow-service/venv/local/lib/python2.7/site-packages/jsonschema-2.6.0-py2.7.egg/jsonschema/validators.py", line 130, in validate
    raise error
jsonschema.exceptions.ValidationError: None is not of type u'string'

Failed validating u'type' in schema[u'items'][u'properties'][u'versions'][u'items'][u'properties'][u'verified-source']:
    {u'description': u'Source of metadata that can support a verified tool, such as an email or URL',
     u'type': u'string'}

On instance[0][u'versions'][0][u'verified-source']:
    None
```

**Comment by denis-yuen** [comment]
Thanks to @tetron
