### ISSUE TITLE
dockstore cromwell-0.21.jar fails on workflow execution with exceptions, while local cromwell-0.28.jar runs WDL workflow without errors

### ISSUE THREAD

**Issue by gabdank** [ga4gh/dockstore#817]
**I am trying to run WDL workflow with cromwell getting the WDL from dockstore.**

(1) Running local Cromwell-0.28.jar results in the following command (that runs successfully):
executing: docker run \
  --rm -i \
   \
  --entrypoint /bin/bash \
  -v /Users/idan/Documents/dockerFiles/cromwell-executions/encode_mapping_workflow/49095f9e-69cd-4229-a2d8-256ba14732e4/call-mapping:/cromwell-executions/encode_mapping_workflow/49095f9e-69cd-4229-a2d8-256ba14732e4/call-mapping \
 quay.io/gabdank/mapping@sha256:2603a7025632ed2ba36e57532a4b0102e1ca7558c3c2a9031bf4a7920845e3cd /cromwell-executions/encode_mapping_workflow/49095f9e-69cd-4229-a2d8-256ba14732e4/call-mapping/execution/script

**while the dockstore Cromwell-0.21.jar results in:**

executing: docker run --rm -v /Users/idan/Documents/dockerFiles/cromwell-executions/encode_mapping_workflow/e843169c-1cd6-4566-bbb0-cb0360cf2fb9/call-mapping:/root/encode_mapping_workflow/e843169c-1cd6-4566-bbb0-cb0360cf2fb9/call-mapping -i quay.io/gabdank/mapping:0622.1 /bin/bash < /Users/idan/Documents/dockerFiles/cromwell-executions/encode_mapping_workflow/e843169c-1cd6-4566-bbb0-cb0360cf2fb9/call-mapping/execution/script

**The local (Cromwell-0.28) runs fine, but the dockstore (Cromwell-0.21) results in:**
`[2017-07-10 10:46:26,02] [info] SharedFileSystemAsyncJobExecutionActor [e843169cencode_mapping_workflow.mapping:NA:1]: command: "/bin/bash" "/Users/idan/Documents/dockerFiles/cromwell-executions/encode_mapping_workflow/e843169c-1cd6-4566-bbb0-cb0360cf2fb9/call-mapping/execution/script.submit"
[2017-07-10 10:46:26,03] [info] SharedFileSystemAsyncJobExecutionActor [e843169cencode_mapping_workflow.mapping:NA:1]: job id: 1832
[2017-07-10 10:46:27,71] [error] WorkflowManagerActor Workflow e843169c-1cd6-4566-bbb0-cb0360cf2fb9 failed (during ExecutingWorkflowState): java.lang.Exception: Call encode_mapping_workflow.mapping: return code was -1
[2017-07-10 10:46:27,71] [info] WorkflowManagerActor WorkflowActor-e843169c-1cd6-4566-bbb0-cb0360cf2fb9 is in a terminal state: WorkflowFailedState
[2017-07-10 10:46:30,10] [info] SingleWorkflowRunnerActor workflow finished with status 'Failed'.
[2017-07-10 10:46:30,11] [error] Workflow e843169c-1cd6-4566-bbb0-cb0360cf2fb9 transitioned to state Failed
java.lang.RuntimeException: Workflow e843169c-1cd6-4566-bbb0-cb0360cf2fb9 transitioned to state Failed
	at cromwell.engine.workflow.SingleWorkflowRunnerActor$RunnerData.addFailure(SingleWorkflowRunnerActor.scala:51)
	at cromwell.engine.workflow.SingleWorkflowRunnerActor$$anonfun$2.applyOrElse(SingleWorkflowRunnerActor.scala:128)
	at cromwell.engine.workflow.SingleWorkflowRunnerActor$$anonfun$2.applyOrElse(SingleWorkflowRunnerActor.scala:106)
	at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:36)
	at akka.actor.FSM$class.processEvent(FSM.scala:663)
	at cromwell.engine.workflow.SingleWorkflowRunnerActor.akka$actor$LoggingFSM$$super$processEvent(SingleWorkflowRunnerActor.scala:68)
	at akka.actor.LoggingFSM$class.processEvent(FSM.scala:799)
	at cromwell.engine.workflow.SingleWorkflowRunnerActor.processEvent(SingleWorkflowRunnerActor.scala:68)
	at akka.actor.FSM$class.akka$actor$FSM$$processMsg(FSM.scala:657)
	at akka.actor.FSM$$anonfun$receive$1.applyOrElse(FSM.scala:651)
	at akka.actor.Actor$class.aroundReceive(Actor.scala:484)
	at cromwell.server.CromwellRootActor.aroundReceive(CromwellRootActor.scala:26)
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:526)
	at akka.actor.ActorCell.invoke(ActorCell.scala:495)
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257)
	at akka.dispatch.Mailbox.run(Mailbox.scala:224)
	at akka.dispatch.Mailbox.exec(Mailbox.scala:234)
	at scala.concurrent.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at scala.concurrent.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at scala.concurrent.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at scala.concurrent.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)

10:46:30.203 [main] ERROR io.dockstore.client.cli.nested.AbstractEntryClient - Problem running cromwell: 
java.lang.RuntimeException: problems running command: java -jar /Users/idan/.dockstore/libraries/cromwell-0.21.jar run /var/folders/53/t0_84q992nv8wv04zr6s7zj00000gp/T/1499708778128-0/overwrittenImports.wdl /var/folders/53/t0_84q992nv8wv04zr6s7zj00000gp/T/foo3019115926818142520json
	at io.dockstore.common.Utilities.executeCommand(Utilities.java:132)
	at io.dockstore.common.Utilities.executeCommand(Utilities.java:83)
	at io.dockstore.client.cli.nested.AbstractEntryClient.launchWdlInternal(AbstractEntryClient.java:1307)
	at io.dockstore.client.cli.nested.WorkflowClient.launch(WorkflowClient.java:331)
	at io.dockstore.client.cli.nested.AbstractEntryClient.processEntryCommands(AbstractEntryClient.java:247)
	at io.dockstore.client.cli.Client.run(Client.java:703)
	at io.dockstore.client.cli.Client.main(Client.java:618)
Caused by: org.apache.commons.exec.ExecuteException: problems running command: java -jar /Users/idan/.dockstore/libraries/cromwell-0.21.jar run /var/folders/53/t0_84q992nv8wv04zr6s7zj00000gp/T/1499708778128-0/overwrittenImports.wdl /var/folders/53/t0_84q992nv8wv04zr6s7zj00000gp/T/foo3019115926818142520json (Exit value: 1)
	at io.dockstore.common.Utilities.executeCommand(Utilities.java:128)
	... 6 common frames omitted
`

**Comment by gabdank** [comment]
The dockstore workflow I am trying to run:
ENCODE-DCC/pipeline-container/encode-mapping-wdl:master

**Comment by gabdank** [comment]
I thin it has something to do with the fact my images have ENTRYPOINT and the tasks in WDL have "commands". 

Why cromwell-0.21 is not specifying entry point lik ecromwell 0.28?

**Comment by denis-yuen** [comment]
I think we simply have to update and test Dockstore with a newer Cromwell release.
In the meantime you could try replacing `~/.dockstore/libraries/cromwell-0.21.jar` with a newer version (not awesome, I know)

**Comment by gabdank** [comment]
worked. the stdout lost indentation but the workflow run with no errors

**Comment by denis-yuen** [comment]
We support Cromwell 29 now in production, so hopefully this (still) works for you
